import img7bf46137e8a0 from '@/assets/7bf46137e8a0.svg';
import img15b85b424519 from '@/assets/15b85b424519.svg';
import img05f1150eb49b from '@/assets/05f1150eb49b.svg';
import imgae89db152e6c from '@/assets/ae89db152e6c.svg';

export default function ChallengeSection() {
  return (
    <>
      <div className="bg-white border-[#e5eaf0] border-b border-solid content-stretch flex flex-col gap-[48px] items-start justify-end px-[48px] py-[72px] relative rounded-[32px] size-full">
        <div className="content-stretch flex flex-col gap-[16px] items-start justify-end relative shrink-0 w-full">
          <div className="content-stretch flex flex-col gap-[16px] items-start relative shrink-0 w-[612px]">
            <div className="[word-break:break-word] flex flex-col justify-center leading-[0] not-italic relative shrink-0 font-['Inter'] font-bold text-[#fd022c] text-[14px] tracking-[1.4px] uppercase whitespace-nowrap "><p className="leading-[20px]">The Challenge</p></div>
            <div className="[word-break:break-word] flex flex-col font-['Roboto'] font-semibold justify-center leading-[0] relative shrink-0 text-[#111] text-[32px] w-full whitespace-pre-wrap" style={{ fontVariationSettings: "'wdth' 100" }}><p className="leading-[1.2] mb-0">Law Enforcement Faces Complex </p><p className="leading-[1.2]">Security Challenges</p></div>
          </div>
          <div className="[word-break:break-word] flex flex-col justify-center leading-[0] not-italic relative shrink-0 font-['Inter'] font-normal text-[#5f6368] text-[16px] w-full whitespace-pre-wrap"><p className="leading-[1.5] mb-0">From crowded public spaces to traffic violations and field operations, </p><p className="leading-[1.5]">officers need access to the right information at the right time.</p></div>
        </div>
        <div className="content-stretch flex gap-[24px] items-start justify-center relative shrink-0 w-full">
          <div className="bg-[#f8f9ff] border border-[#e5e5e5] border-solid content-stretch drop-shadow-[0px_4px_10px_rgba(11,31,58,0.04)] flex flex-[1_0_0] flex-col gap-[16px] items-start min-w-px p-[25px] relative rounded-[16px]">
            <div className="bg-[#fff1f2] content-stretch flex items-center justify-center relative rounded-[12px] shrink-0 size-[48px]"><div className="h-[23.333px] relative shrink-0 w-[18.667px]"><img alt="" className="absolute block inset-0 max-w-none size-full" src={img7bf46137e8a0} /></div></div>
            <div className="content-stretch flex flex-col items-start pt-[8px] relative shrink-0 w-full"><div className="[word-break:break-word] flex flex-col font-['Manrope'] font-semibold justify-center leading-[0] relative shrink-0 text-[#111] text-[20px] w-full"><p className="leading-[28px] mb-0">Infrastructure</p><p className="leading-[28px]">Protection</p></div></div>
            <div className="content-stretch flex flex-col gap-[12px] items-start relative shrink-0 w-full">
                <div className="h-[42px] relative shrink-0 w-full"><div className="absolute h-[8.017px] left-[2.57px] top-[5.98px] w-[10.867px]"><img alt="" className="absolute block inset-0 max-w-none size-full" src={img15b85b424519} /></div><div className="-translate-y-1/2 [word-break:break-word] absolute flex flex-col font-['Inter'] font-normal justify-center leading-[0] left-[24px] not-italic text-[#5f6368] text-[14px] top-[21px] whitespace-nowrap"><p className="leading-[21px] mb-0">High-definition CCTV across</p><p className="leading-[21px]">critical infrastructure</p></div></div>
                <div className="h-[42px] relative shrink-0 w-full"><div className="absolute h-[8.017px] left-[2.57px] top-[5.98px] w-[10.867px]"><img alt="" className="absolute block inset-0 max-w-none size-full" src={img15b85b424519} /></div><div className="-translate-y-1/2 [word-break:break-word] absolute flex flex-col font-['Inter'] font-normal justify-center leading-[0] left-[24px] not-italic text-[#5f6368] text-[14px] top-[21px] whitespace-nowrap"><p className="leading-[21px] mb-0">Protect roads, railways,</p><p className="leading-[21px]">waterways &amp; public assets</p></div></div>
            </div>
          </div>
          <div className="bg-[#f8f9ff] border border-[#e5e5e5] border-solid content-stretch drop-shadow-[0px_4px_10px_rgba(11,31,58,0.04)] flex flex-[1_0_0] flex-col gap-[16px] items-start min-w-px p-[25px] relative rounded-[16px]">
            <div className="bg-[#fff1f2] content-stretch flex items-center justify-center relative rounded-[12px] shrink-0 size-[48px]"><div className="h-[23.333px] relative shrink-0 w-[18.667px]"><img alt="" className="absolute block inset-0 max-w-none size-full" src={img7bf46137e8a0} /></div></div>
            <div className="content-stretch flex flex-col items-start pt-[8px] relative shrink-0 w-full"><div className="[word-break:break-word] flex flex-col font-['Manrope'] font-semibold justify-center leading-[0] relative shrink-0 text-[#111] text-[20px] w-full"><p className="leading-[28px] mb-0">Traffic &amp; Road</p><p className="leading-[28px]">Intelligence</p></div></div>
            <div className="content-stretch flex flex-col gap-[12px] items-start relative shrink-0 w-full">
                <div className="h-[42px] relative shrink-0 w-full"><div className="absolute h-[8.017px] left-[2.57px] top-[5.98px] w-[10.867px]"><img alt="" className="absolute block inset-0 max-w-none size-full" src={img15b85b424519} /></div><div className="-translate-y-1/2 [word-break:break-word] absolute flex flex-col font-['Inter'] font-normal justify-center leading-[0] left-[24px] not-italic text-[#5f6368] text-[14px] top-[21px] whitespace-nowrap"><p className="leading-[21px] mb-0">Monitor traffic flow &amp; queue</p><p className="leading-[21px]">lengths</p></div></div>
                <div className="h-[42px] relative shrink-0 w-full"><div className="absolute h-[8.017px] left-[2.57px] top-[5.98px] w-[10.867px]"><img alt="" className="absolute block inset-0 max-w-none size-full" src={img15b85b424519} /></div><div className="-translate-y-1/2 [word-break:break-word] absolute flex flex-col font-['Inter'] font-normal justify-center leading-[0] left-[24px] not-italic text-[#5f6368] text-[14px] top-[21px] whitespace-nowrap"><p className="leading-[21px] mb-0">Detect incidents &amp; violations in</p><p className="leading-[21px]">real-time</p></div></div>
            </div>
          </div>
          <div className="bg-[#f8f9ff] border border-[#e5e5e5] border-solid content-stretch drop-shadow-[0px_4px_10px_rgba(11,31,58,0.04)] flex flex-[1_0_0] flex-col gap-[16px] items-start min-w-px pb-[53px] pt-[25px] px-[25px] relative rounded-[16px]">
            <div className="bg-[#fff1f2] content-stretch flex items-center justify-center relative rounded-[12px] shrink-0 size-[48px]"><div className="flex flex-[1_0_0] h-[48.438px] items-center justify-center min-w-px relative"><div className="flex-none rotate-[0.53deg] w-full"><div className="aspect-square bg-[#fff1f2] content-stretch flex flex-col items-center justify-center overflow-clip py-[4px] relative rounded-[60000px] size-full"><div className="h-[24px] relative shrink-0 w-[19.765px]"><img alt="" className="absolute block inset-0 max-w-none size-full" src={img05f1150eb49b} /></div></div></div></div></div>
            <div className="content-stretch flex flex-col items-start pt-[8px] relative shrink-0 w-full"><div className="[word-break:break-word] flex flex-col font-['Manrope'] font-semibold justify-center leading-[0] relative shrink-0 text-[#111] text-[20px] w-full"><p className="leading-[28px]">Transport Security</p></div></div>
            <div className="content-stretch flex flex-col gap-[12px] items-start relative shrink-0 w-full">
                <div className="h-[42px] relative shrink-0 w-full"><div className="absolute h-[8.017px] left-[2.57px] top-[5.98px] w-[10.867px]"><img alt="" className="absolute block inset-0 max-w-none size-full" src={img15b85b424519} /></div><div className="-translate-y-1/2 [word-break:break-word] absolute flex flex-col font-['Inter'] font-normal justify-center leading-[0] left-[24px] not-italic text-[#5f6368] text-[14px] top-[21px] whitespace-nowrap"><p className="leading-[21px] mb-0">AI analytics to identify threats</p><p className="leading-[21px]">in transit</p></div></div>
                <div className="h-[42px] relative shrink-0 w-full"><div className="absolute h-[8.017px] left-[2.57px] top-[5.98px] w-[10.867px]"><img alt="" className="absolute block inset-0 max-w-none size-full" src={img15b85b424519} /></div><div className="-translate-y-1/2 [word-break:break-word] absolute flex flex-col font-['Inter'] font-normal justify-center leading-[0] left-[24px] not-italic text-[#5f6368] text-[14px] top-[21px] whitespace-nowrap"><p className="leading-[21px] mb-0">Enhance passenger &amp; asset</p><p className="leading-[21px]">safety</p></div></div>
            </div>
          </div>
          <div className="bg-[#f8f9ff] border border-[#e5e5e5] border-solid content-stretch drop-shadow-[0px_4px_10px_rgba(11,31,58,0.04)] flex flex-[1_0_0] flex-col gap-[16px] items-start min-w-px pb-[53px] pt-[25px] px-[25px] relative rounded-[16px]">
            <div className="bg-[#fff1f2] content-stretch flex items-center justify-center relative rounded-[12px] shrink-0 size-[48px]"><div className="flex flex-[1_0_0] h-[48.438px] items-center justify-center min-w-px relative"><div className="flex-none rotate-[0.53deg] w-full"><div className="aspect-square relative size-full"><img alt="" className="absolute block inset-0 max-w-none size-full" src={imgae89db152e6c} /></div></div></div></div>
            <div className="content-stretch flex flex-col items-start pt-[8px] relative shrink-0 w-full"><div className="[word-break:break-word] flex flex-col font-['Manrope'] font-semibold justify-center leading-[0] relative shrink-0 text-[#111] text-[20px] w-full"><p className="leading-[28px]">Emergency Response</p></div></div>
            <div className="content-stretch flex flex-col gap-[12px] items-start relative shrink-0 w-full">
                <div className="h-[42px] relative shrink-0 w-full"><div className="absolute h-[8.017px] left-[2.57px] top-[5.98px] w-[10.867px]"><img alt="" className="absolute block inset-0 max-w-none size-full" src={img15b85b424519} /></div><div className="-translate-y-1/2 [word-break:break-word] absolute flex flex-col font-['Inter'] font-normal justify-center leading-[0] left-[24px] not-italic text-[#5f6368] text-[14px] top-[21px] whitespace-nowrap"><p className="leading-[21px] mb-0">AVL &amp; GPS tracking for</p><p className="leading-[21px]">emergency vehicles</p></div></div>
                <div className="h-[42px] relative shrink-0 w-full"><div className="absolute h-[8.017px] left-[2.57px] top-[5.98px] w-[10.867px]"><img alt="" className="absolute block inset-0 max-w-none size-full" src={img15b85b424519} /></div><div className="-translate-y-1/2 [word-break:break-word] absolute flex flex-col font-['Inter'] font-normal justify-center leading-[0] left-[24px] not-italic text-[#5f6368] text-[14px] top-[21px] whitespace-nowrap"><p className="leading-[21px] mb-0">Faster dispatch &amp; route</p><p className="leading-[21px]">optimization</p></div></div>
            </div>
          </div>
        </div>
      </div>
    </>
  );
}
