import imge1579c4f66ff from '@/assets/e1579c4f66ff.jpg';
import img145feba0f147 from '@/assets/145feba0f147.jpg';
import imgd7d29952d3e4 from '@/assets/d7d29952d3e4.jpg';
import imgfdd0381e6d92 from '@/assets/fdd0381e6d92.jpg';
import imge20d370ec929 from '@/assets/e20d370ec929.jpg';
import imge3c1362d0d45 from '@/assets/e3c1362d0d45.jpg';
import imgc9ae281a3c7c from '@/assets/c9ae281a3c7c.jpg';
import imgabcfeca71284 from '@/assets/abcfeca71284.jpg';
import img2698b75cd3b1 from '@/assets/2698b75cd3b1.jpg';
import img3544372595cc from '@/assets/3544372595cc.jpg';

export default function ComponentsSection() {
  return (
    <>
      <div className="bg-white content-stretch flex flex-col items-start px-[72px] py-[80px] relative size-full">
        <div className="content-stretch flex flex-col gap-[48px] items-start px-[32px] relative shrink-0 w-full">
          <div className="content-stretch flex flex-col gap-[16px] items-start relative shrink-0 w-full">
            <div className="content-stretch flex flex-col items-center relative shrink-0 w-full"><div className="[word-break:break-word] flex flex-col font-['Roboto'] font-semibold justify-center leading-[0] relative shrink-0 text-[#111] text-[32px] text-center whitespace-nowrap" style={{ fontVariationSettings: "'wdth' 100" }}><h2 className="leading-[1.2]">OUR SOLUTION COMPONENTS</h2></div></div>
            <div className="[word-break:break-word] flex flex-col font-['Inter'] font-normal justify-center leading-[0] not-italic relative shrink-0 text-[#5f6368] text-[16px] text-center w-full"><p className="leading-[1.5]">Traditional traffic systems are reactive. HOUM uses advanced<br />edge computing and deep learning to instantly analyze video<br />feeds, identify patterns, and trigger automated responses before<br />congestion or safety incidents escalate.</p></div>
          </div>
          <div className="content-stretch flex flex-col gap-[32px] items-center relative shrink-0 w-full">
        <div className="bg-white border border-[#e5e7eb] border-solid content-start drop-shadow-[0px_4px_10px_rgba(0,0,0,0.05)] flex flex-wrap gap-[48px] items-start justify-center p-[33px] relative rounded-[12px] shrink-0 w-full">
          <div className="bg-white drop-shadow-[0px_4px_10px_rgba(0,0,0,0.1)] flex h-[354px] items-start overflow-clip relative rounded-[24px] shrink-0 w-[515px]"><div className="flex-[1_0_0] h-full min-w-px relative"><img alt="HOUM camera" className="absolute inset-0 max-w-none object-contain pointer-events-none size-full" src={imge1579c4f66ff} /></div><div className="flex-[1_0_0] h-full min-w-px relative"><img alt="HOUM camera" className="absolute inset-0 max-w-none object-contain pointer-events-none size-full" src={img145feba0f147} /></div></div>
          <div className="content-stretch flex flex-col gap-[16px] items-start relative shrink-0 w-[556px]">
            <div className="content-stretch flex flex-col gap-[8px] items-start relative shrink-0 w-full">
              <div className="[word-break:break-word] flex flex-col font-['Inter'] font-bold justify-center leading-[0] not-italic relative shrink-0 text-[#fd022c] text-[14px] tracking-[1.4px] uppercase w-full"><p className="leading-[20px]">01 &mdash; Smart Surveillance Cameras</p></div>
              <div className="[word-break:break-word] flex flex-col font-['Poppins'] justify-center leading-[0] not-italic relative shrink-0 text-[#111] text-[24px] w-full"><h3 className="leading-[1.2]">Flexible monitoring for transport environments</h3></div>
            </div>
            <div className="[word-break:break-word] content-stretch flex flex-col font-['Inter'] font-normal gap-[8px] items-start leading-[0] not-italic relative shrink-0 w-full">
              <div className="content-stretch flex flex-col gap-[4px] items-start relative shrink-0 w-full">
                <div className="flex flex-col justify-center relative shrink-0 text-[#111] text-[16px] w-full"><p className="leading-[1.5]">HOUM-K261 / HOUM-P161</p></div>
                <div className="flex flex-col justify-center relative shrink-0 text-[#3f4347] text-[14px] w-full"><p className="font-['Inter'] italic leading-[20px] text-[14px]">Smart Fixed &amp; PT Cameras</p></div>
              </div>
            </div>
            <div className="content-stretch flex flex-col gap-[4px] items-start pl-[16px] relative shrink-0 w-full">
                <div className="[word-break:break-word] content-stretch flex gap-[10px] items-center leading-[0] relative shrink-0 text-[12px] whitespace-nowrap"><div className="flex flex-col font-['Inter'] font-normal justify-center not-italic relative shrink-0 text-[#5f6368]"><p className="leading-[1.5]">Up to 5MP resolution</p></div><div className="-translate-y-1/2 absolute flex flex-col font-['Manrope'] font-bold justify-center left-[-12px] text-[#fd022c] top-[8px]"><p className="leading-[16px]">&bull;</p></div></div>
                <div className="[word-break:break-word] content-stretch flex gap-[10px] items-center leading-[0] relative shrink-0 text-[12px] whitespace-nowrap"><div className="flex flex-col font-['Inter'] font-normal justify-center not-italic relative shrink-0 text-[#5f6368]"><p className="leading-[1.5]">Wide viewing angle</p></div><div className="-translate-y-1/2 absolute flex flex-col font-['Manrope'] font-bold justify-center left-[-12px] text-[#fd022c] top-[8px]"><p className="leading-[16px]">&bull;</p></div></div>
                <div className="[word-break:break-word] content-stretch flex gap-[10px] items-center leading-[0] relative shrink-0 text-[12px] whitespace-nowrap"><div className="flex flex-col font-['Inter'] font-normal justify-center not-italic relative shrink-0 text-[#5f6368]"><p className="leading-[1.5]">Motion detection</p></div><div className="-translate-y-1/2 absolute flex flex-col font-['Manrope'] font-bold justify-center left-[-12px] text-[#fd022c] top-[8px]"><p className="leading-[16px]">&bull;</p></div></div>
                <div className="[word-break:break-word] content-stretch flex gap-[10px] items-center leading-[0] relative shrink-0 text-[12px] whitespace-nowrap"><div className="flex flex-col font-['Inter'] font-normal justify-center not-italic relative shrink-0 text-[#5f6368]"><p className="leading-[1.5]">Moving tracking on supported PT models</p></div><div className="-translate-y-1/2 absolute flex flex-col font-['Manrope'] font-bold justify-center left-[-12px] text-[#fd022c] top-[8px]"><p className="leading-[16px]">&bull;</p></div></div>
                <div className="[word-break:break-word] content-stretch flex gap-[10px] items-center leading-[0] relative shrink-0 text-[12px] whitespace-nowrap"><div className="flex flex-col font-['Inter'] font-normal justify-center not-italic relative shrink-0 text-[#5f6368]"><p className="leading-[1.5]">Two-way audio</p></div><div className="-translate-y-1/2 absolute flex flex-col font-['Manrope'] font-bold justify-center left-[-12px] text-[#fd022c] top-[8px]"><p className="leading-[16px]">&bull;</p></div></div>
                <div className="[word-break:break-word] content-stretch flex gap-[10px] items-center leading-[0] relative shrink-0 text-[12px] whitespace-nowrap"><div className="flex flex-col font-['Inter'] font-normal justify-center not-italic relative shrink-0 text-[#5f6368]"><p className="leading-[1.5]">Remote viewing</p></div><div className="-translate-y-1/2 absolute flex flex-col font-['Manrope'] font-bold justify-center left-[-12px] text-[#fd022c] top-[8px]"><p className="leading-[16px]">&bull;</p></div></div>
            </div>
            <div className="content-start flex flex-wrap gap-y-[8px] items-start relative shrink-0 w-full">
              <div className="content-stretch flex flex-col gap-[8px] items-start justify-center relative shrink-0">
                <div className="[word-break:break-word] flex flex-col font-['Inter'] font-normal justify-center leading-[0] not-italic relative shrink-0 text-[#111] text-[12px] whitespace-nowrap"><p className="leading-[1.5]">Use cases:</p></div>
                <div className="content-stretch flex gap-[8px] items-start relative shrink-0"><div className="[word-break:break-word] flex flex-col font-['Inter'] font-normal justify-center leading-[0] not-italic relative shrink-0 text-[#5f6368] text-[12px] whitespace-nowrap"><p className="leading-[1.5]">Transport Hubs</p></div><div className="[word-break:break-word] flex flex-col font-['Inter'] font-medium justify-center leading-[0] not-italic relative shrink-0 text-[#5f6368] text-[14px] whitespace-nowrap"><p className="leading-[1.2]">&middot;</p></div><div className="[word-break:break-word] flex flex-col font-['Inter'] font-normal justify-center leading-[0] not-italic relative shrink-0 text-[#5f6368] text-[12px] whitespace-nowrap"><p className="leading-[1.5]">Offices</p></div><div className="[word-break:break-word] flex flex-col font-['Inter'] font-medium justify-center leading-[0] not-italic relative shrink-0 text-[#5f6368] text-[14px] whitespace-nowrap"><p className="leading-[1.2]">&middot;</p></div><div className="[word-break:break-word] flex flex-col font-['Inter'] font-normal justify-center leading-[0] not-italic relative shrink-0 text-[#5f6368] text-[12px] whitespace-nowrap"><p className="leading-[1.5]">Waiting Areas</p></div></div>
              </div>
            </div>
          </div>
        </div>
        <div className="bg-white border border-[#e5e7eb] border-solid content-start drop-shadow-[0px_4px_10px_rgba(0,0,0,0.05)] flex flex-wrap gap-[48px] items-start justify-center p-[33px] relative rounded-[12px] shrink-0 w-full">
          <div className="content-stretch flex flex-col gap-[16px] items-start relative shrink-0 w-[556px]">
            <div className="content-stretch flex flex-col gap-[8px] items-start relative shrink-0 w-full">
              <div className="[word-break:break-word] flex flex-col font-['Inter'] font-bold justify-center leading-[0] not-italic relative shrink-0 text-[#fd022c] text-[14px] tracking-[1.4px] uppercase w-full"><p className="leading-[20px]">02 &mdash; PTZ &amp; Wide-Area Monitoring</p></div>
              <div className="[word-break:break-word] flex flex-col font-['Poppins'] justify-center leading-[0] not-italic relative shrink-0 text-[#111] text-[24px] w-full"><h3 className="leading-[1.2]">Cover larger areas with flexible camera movement</h3></div>
            </div>
            <div className="[word-break:break-word] content-stretch flex flex-col font-['Inter'] font-normal gap-[8px] items-start leading-[0] not-italic relative shrink-0 w-full">
              <div className="content-stretch flex flex-col gap-[4px] items-start relative shrink-0 w-full">
                <div className="flex flex-col justify-center relative shrink-0 text-[#111] text-[16px] w-full"><p className="leading-[1.5]">HOUM-K195 / HOUM-P163</p></div>
                <div className="flex flex-col justify-center relative shrink-0 text-[#3f4347] text-[14px] w-full"><p className="font-['Inter'] italic leading-[20px] text-[14px]">Smart PTZ Indoor Cameras</p></div>
              </div>
            </div>
            <div className="content-stretch flex flex-col gap-[4px] items-start pl-[16px] relative shrink-0 w-full">
                <div className="[word-break:break-word] content-stretch flex gap-[10px] items-center leading-[0] relative shrink-0 text-[12px] whitespace-nowrap"><div className="flex flex-col font-['Inter'] font-normal justify-center not-italic relative shrink-0 text-[#5f6368]"><p className="leading-[1.5]">Up to 5MP resolution</p></div><div className="-translate-y-1/2 absolute flex flex-col font-['Manrope'] font-bold justify-center left-[-12px] text-[#fd022c] top-[8px]"><p className="leading-[16px]">&bull;</p></div></div>
                <div className="[word-break:break-word] content-stretch flex gap-[10px] items-center leading-[0] relative shrink-0 text-[12px] whitespace-nowrap"><div className="flex flex-col font-['Inter'] font-normal justify-center not-italic relative shrink-0 text-[#5f6368]"><p className="leading-[1.5]">355&deg; horizontal coverage</p></div><div className="-translate-y-1/2 absolute flex flex-col font-['Manrope'] font-bold justify-center left-[-12px] text-[#fd022c] top-[8px]"><p className="leading-[16px]">&bull;</p></div></div>
                <div className="[word-break:break-word] content-stretch flex gap-[10px] items-center leading-[0] relative shrink-0 text-[12px] whitespace-nowrap"><div className="flex flex-col font-['Inter'] font-normal justify-center not-italic relative shrink-0 text-[#5f6368]"><p className="leading-[1.5]">Motion detection</p></div><div className="-translate-y-1/2 absolute flex flex-col font-['Manrope'] font-bold justify-center left-[-12px] text-[#fd022c] top-[8px]"><p className="leading-[16px]">&bull;</p></div></div>
                <div className="[word-break:break-word] content-stretch flex gap-[10px] items-center leading-[0] relative shrink-0 text-[12px] whitespace-nowrap"><div className="flex flex-col font-['Inter'] font-normal justify-center not-italic relative shrink-0 text-[#5f6368]"><p className="leading-[1.5]">Up to 80&deg; vertical coverage</p></div><div className="-translate-y-1/2 absolute flex flex-col font-['Manrope'] font-bold justify-center left-[-12px] text-[#fd022c] top-[8px]"><p className="leading-[16px]">&bull;</p></div></div>
                <div className="[word-break:break-word] content-stretch flex gap-[10px] items-center leading-[0] relative shrink-0 text-[12px] whitespace-nowrap"><div className="flex flex-col font-['Inter'] font-normal justify-center not-italic relative shrink-0 text-[#5f6368]"><p className="leading-[1.5]">Moving tracking</p></div><div className="-translate-y-1/2 absolute flex flex-col font-['Manrope'] font-bold justify-center left-[-12px] text-[#fd022c] top-[8px]"><p className="leading-[16px]">&bull;</p></div></div>
                <div className="[word-break:break-word] content-stretch flex gap-[10px] items-center leading-[0] relative shrink-0 text-[12px] whitespace-nowrap"><div className="flex flex-col font-['Inter'] font-normal justify-center not-italic relative shrink-0 text-[#5f6368]"><p className="leading-[1.5]">Remote viewing &amp; control</p></div><div className="-translate-y-1/2 absolute flex flex-col font-['Manrope'] font-bold justify-center left-[-12px] text-[#fd022c] top-[8px]"><p className="leading-[16px]">&bull;</p></div></div>
            </div>
            <div className="content-start flex flex-wrap gap-y-[8px] items-start relative shrink-0 w-full">
              <div className="content-stretch flex flex-col gap-[8px] items-start justify-center relative shrink-0">
                <div className="[word-break:break-word] flex flex-col font-['Inter'] font-normal justify-center leading-[0] not-italic relative shrink-0 text-[#111] text-[12px] whitespace-nowrap"><p className="leading-[1.5]">Use cases:</p></div>
                <div className="content-stretch flex gap-[8px] items-start relative shrink-0"><div className="[word-break:break-word] flex flex-col font-['Inter'] font-normal justify-center leading-[0] not-italic relative shrink-0 text-[#5f6368] text-[12px] whitespace-nowrap"><p className="leading-[1.5]">Terminals</p></div><div className="[word-break:break-word] flex flex-col font-['Inter'] font-medium justify-center leading-[0] not-italic relative shrink-0 text-[#5f6368] text-[14px] whitespace-nowrap"><p className="leading-[1.2]">&middot;</p></div><div className="[word-break:break-word] flex flex-col font-['Inter'] font-normal justify-center leading-[0] not-italic relative shrink-0 text-[#5f6368] text-[12px] whitespace-nowrap"><p className="leading-[1.5]">Large Indoor Areas</p></div><div className="[word-break:break-word] flex flex-col font-['Inter'] font-medium justify-center leading-[0] not-italic relative shrink-0 text-[#5f6368] text-[14px] whitespace-nowrap"><p className="leading-[1.2]">&middot;</p></div><div className="[word-break:break-word] flex flex-col font-['Inter'] font-normal justify-center leading-[0] not-italic relative shrink-0 text-[#5f6368] text-[12px] whitespace-nowrap"><p className="leading-[1.5]">Passenger Zones</p></div></div>
              </div>
            </div>
          </div>
          <div className="bg-white drop-shadow-[0px_4px_10px_rgba(0,0,0,0.1)] flex h-[354px] items-start overflow-clip relative rounded-[24px] shrink-0 w-[515px]"><div className="flex-[1_0_0] h-full min-w-px relative"><img alt="HOUM camera" className="absolute inset-0 max-w-none object-contain pointer-events-none size-full" src={imgd7d29952d3e4} /></div><div className="flex-[1_0_0] h-full min-w-px relative"><img alt="HOUM camera" className="absolute inset-0 max-w-none object-contain pointer-events-none size-full" src={imgfdd0381e6d92} /></div></div>
        </div>
        <div className="bg-white border border-[#e5e7eb] border-solid content-start drop-shadow-[0px_4px_10px_rgba(0,0,0,0.05)] flex flex-wrap gap-[48px] items-start justify-center p-[33px] relative rounded-[12px] shrink-0 w-full">
          <div className="bg-white drop-shadow-[0px_4px_10px_rgba(0,0,0,0.1)] flex h-[325px] items-start overflow-clip relative rounded-[24px] shrink-0 w-[515px]"><div className="flex-[1_0_0] h-full min-w-px relative"><img alt="HOUM camera" className="absolute inset-0 max-w-none object-contain pointer-events-none size-full" src={imge20d370ec929} /></div><div className="flex-[1_0_0] h-full min-w-px relative"><img alt="HOUM camera" className="absolute inset-0 max-w-none object-contain pointer-events-none size-full" src={imge3c1362d0d45} /></div></div>
          <div className="content-stretch flex flex-col gap-[16px] items-start relative shrink-0 w-[556px]">
            <div className="content-stretch flex flex-col gap-[8px] items-start relative shrink-0 w-full">
              <div className="[word-break:break-word] flex flex-col font-['Inter'] font-bold justify-center leading-[0] not-italic relative shrink-0 text-[#fd022c] text-[14px] tracking-[1.4px] uppercase w-full"><p className="leading-[20px]">03 &mdash; Outdoor Surveillance</p></div>
              <div className="[word-break:break-word] flex flex-col font-['Poppins'] justify-center leading-[0] not-italic relative shrink-0 text-[#111] text-[24px] w-full"><h3 className="leading-[1.2]">Reliable protection across external areas</h3></div>
            </div>
            <div className="[word-break:break-word] content-stretch flex flex-col font-['Inter'] font-normal gap-[8px] items-start leading-[0] not-italic relative shrink-0 w-full">
              <div className="content-stretch flex flex-col gap-[4px] items-start relative shrink-0 w-full">
                <div className="flex flex-col justify-center relative shrink-0 text-[#111] text-[16px] w-full"><p className="leading-[1.5]">HOUM-K233 / HOUM-PL01 / HOUM-GL09</p></div>
                <div className="flex flex-col justify-center relative shrink-0 text-[#3f4347] text-[14px] w-full"><p className="font-['Inter'] italic leading-[20px] text-[14px]">Outdoor Smart Cameras</p></div>
              </div>
            </div>
            <div className="content-stretch flex flex-col gap-[4px] items-start pl-[16px] relative shrink-0 w-full">
                <div className="[word-break:break-word] content-stretch flex gap-[10px] items-center leading-[0] relative shrink-0 text-[12px] whitespace-nowrap"><div className="flex flex-col font-['Inter'] font-normal justify-center not-italic relative shrink-0 text-[#5f6368]"><p className="leading-[1.5]">Up to 4MP resolution</p></div><div className="-translate-y-1/2 absolute flex flex-col font-['Manrope'] font-bold justify-center left-[-12px] text-[#fd022c] top-[8px]"><p className="leading-[16px]">&bull;</p></div></div>
                <div className="[word-break:break-word] content-stretch flex gap-[10px] items-center leading-[0] relative shrink-0 text-[12px] whitespace-nowrap"><div className="flex flex-col font-['Inter'] font-normal justify-center not-italic relative shrink-0 text-[#5f6368]"><p className="leading-[1.5]">Night vision options</p></div><div className="-translate-y-1/2 absolute flex flex-col font-['Manrope'] font-bold justify-center left-[-12px] text-[#fd022c] top-[8px]"><p className="leading-[16px]">&bull;</p></div></div>
                <div className="[word-break:break-word] content-stretch flex gap-[10px] items-center leading-[0] relative shrink-0 text-[12px] whitespace-nowrap"><div className="flex flex-col font-['Inter'] font-normal justify-center not-italic relative shrink-0 text-[#5f6368]"><p className="leading-[1.5]">Motion detection</p></div><div className="-translate-y-1/2 absolute flex flex-col font-['Manrope'] font-bold justify-center left-[-12px] text-[#fd022c] top-[8px]"><p className="leading-[16px]">&bull;</p></div></div>
                <div className="[word-break:break-word] content-stretch flex gap-[10px] items-center leading-[0] relative shrink-0 text-[12px] whitespace-nowrap"><div className="flex flex-col font-['Inter'] font-normal justify-center not-italic relative shrink-0 text-[#5f6368]"><p className="leading-[1.5]">Auto-tracking on supported models</p></div><div className="-translate-y-1/2 absolute flex flex-col font-['Manrope'] font-bold justify-center left-[-12px] text-[#fd022c] top-[8px]"><p className="leading-[16px]">&bull;</p></div></div>
                <div className="[word-break:break-word] content-stretch flex gap-[10px] items-center leading-[0] relative shrink-0 text-[12px] whitespace-nowrap"><div className="flex flex-col font-['Inter'] font-normal justify-center not-italic relative shrink-0 text-[#5f6368]"><p className="leading-[1.5]">Object &amp; area detection on PL01/GL09</p></div><div className="-translate-y-1/2 absolute flex flex-col font-['Manrope'] font-bold justify-center left-[-12px] text-[#fd022c] top-[8px]"><p className="leading-[16px]">&bull;</p></div></div>
                <div className="[word-break:break-word] content-stretch flex gap-[10px] items-center leading-[0] relative shrink-0 text-[12px] whitespace-nowrap"><div className="flex flex-col font-['Inter'] font-normal justify-center not-italic relative shrink-0 text-[#5f6368]"><p className="leading-[1.5]">IP65 outdoor protection on PL01/GL09</p></div><div className="-translate-y-1/2 absolute flex flex-col font-['Manrope'] font-bold justify-center left-[-12px] text-[#fd022c] top-[8px]"><p className="leading-[16px]">&bull;</p></div></div>
            </div>
            <div className="content-start flex flex-wrap gap-y-[8px] items-start relative shrink-0 w-full">
              <div className="content-stretch flex flex-col gap-[8px] items-start justify-center relative shrink-0">
                <div className="[word-break:break-word] flex flex-col font-['Inter'] font-normal justify-center leading-[0] not-italic relative shrink-0 text-[#111] text-[12px] whitespace-nowrap"><p className="leading-[1.5]">Use cases:</p></div>
                <div className="content-stretch flex gap-[8px] items-start relative shrink-0"><div className="[word-break:break-word] flex flex-col font-['Inter'] font-normal justify-center leading-[0] not-italic relative shrink-0 text-[#5f6368] text-[12px] whitespace-nowrap"><p className="leading-[1.5]">Parking Areas</p></div><div className="[word-break:break-word] flex flex-col font-['Inter'] font-medium justify-center leading-[0] not-italic relative shrink-0 text-[#5f6368] text-[14px] whitespace-nowrap"><p className="leading-[1.2]">&middot;</p></div><div className="[word-break:break-word] flex flex-col font-['Inter'] font-normal justify-center leading-[0] not-italic relative shrink-0 text-[#5f6368] text-[12px] whitespace-nowrap"><p className="leading-[1.5]">Depots</p></div><div className="[word-break:break-word] flex flex-col font-['Inter'] font-medium justify-center leading-[0] not-italic relative shrink-0 text-[#5f6368] text-[14px] whitespace-nowrap"><p className="leading-[1.2]">&middot;</p></div><div className="[word-break:break-word] flex flex-col font-['Inter'] font-normal justify-center leading-[0] not-italic relative shrink-0 text-[#5f6368] text-[12px] whitespace-nowrap"><p className="leading-[1.5]">Entry Points</p></div></div>
              </div>
            </div>
          </div>
        </div>
        <div className="bg-white border border-[#e5e7eb] border-solid content-start drop-shadow-[0px_4px_10px_rgba(0,0,0,0.05)] flex flex-wrap gap-[48px] items-start justify-center p-[33px] relative rounded-[12px] shrink-0 w-full">
          <div className="content-stretch flex flex-col gap-[16px] items-start relative shrink-0 w-[556px]">
            <div className="content-stretch flex flex-col gap-[8px] items-start relative shrink-0 w-full">
              <div className="[word-break:break-word] flex flex-col font-['Inter'] font-bold justify-center leading-[0] not-italic relative shrink-0 text-[#fd022c] text-[14px] tracking-[1.4px] uppercase w-full"><p className="leading-[20px]">04 &mdash; 4G Remote Surveillance</p></div>
              <div className="[word-break:break-word] flex flex-col font-['Poppins'] justify-center leading-[0] not-italic relative shrink-0 text-[#111] text-[24px] w-full"><h3 className="leading-[1.2]">Stay connected where wired networks aren&apos;t available</h3></div>
            </div>
            <div className="[word-break:break-word] content-stretch flex flex-col font-['Inter'] font-normal gap-[8px] items-start leading-[0] not-italic relative shrink-0 w-full">
              <div className="content-stretch flex flex-col gap-[4px] items-start relative shrink-0 w-full">
                <div className="flex flex-col justify-center relative shrink-0 text-[#111] text-[16px] w-full"><p className="leading-[1.5]">HOUM-P168 / HOUM-170 / HOUM-170S</p></div>
                <div className="flex flex-col justify-center relative shrink-0 text-[#3f4347] text-[14px] w-full"><p className="font-['Inter'] italic leading-[20px] text-[14px]">4G Outdoor Cameras</p></div>
              </div>
            </div>
            <div className="content-stretch flex flex-col gap-[4px] items-start pl-[16px] relative shrink-0 w-full">
                <div className="[word-break:break-word] content-stretch flex gap-[10px] items-center leading-[0] relative shrink-0 text-[12px] whitespace-nowrap"><div className="flex flex-col font-['Inter'] font-normal justify-center not-italic relative shrink-0 text-[#5f6368]"><p className="leading-[1.5]">4G connectivity</p></div><div className="-translate-y-1/2 absolute flex flex-col font-['Manrope'] font-bold justify-center left-[-12px] text-[#fd022c] top-[8px]"><p className="leading-[16px]">&bull;</p></div></div>
                <div className="[word-break:break-word] content-stretch flex gap-[10px] items-center leading-[0] relative shrink-0 text-[12px] whitespace-nowrap"><div className="flex flex-col font-['Inter'] font-normal justify-center not-italic relative shrink-0 text-[#5f6368]"><p className="leading-[1.5]">Wide viewing angle</p></div><div className="-translate-y-1/2 absolute flex flex-col font-['Manrope'] font-bold justify-center left-[-12px] text-[#fd022c] top-[8px]"><p className="leading-[16px]">&bull;</p></div></div>
                <div className="[word-break:break-word] content-stretch flex gap-[10px] items-center leading-[0] relative shrink-0 text-[12px] whitespace-nowrap"><div className="flex flex-col font-['Inter'] font-normal justify-center not-italic relative shrink-0 text-[#5f6368]"><p className="leading-[1.5]">Motion detection</p></div><div className="-translate-y-1/2 absolute flex flex-col font-['Manrope'] font-bold justify-center left-[-12px] text-[#fd022c] top-[8px]"><p className="leading-[16px]">&bull;</p></div></div>
                <div className="[word-break:break-word] content-stretch flex gap-[10px] items-center leading-[0] relative shrink-0 text-[12px] whitespace-nowrap"><div className="flex flex-col font-['Inter'] font-normal justify-center not-italic relative shrink-0 text-[#5f6368]"><p className="leading-[1.5]">Remote viewing</p></div><div className="-translate-y-1/2 absolute flex flex-col font-['Manrope'] font-bold justify-center left-[-12px] text-[#fd022c] top-[8px]"><p className="leading-[16px]">&bull;</p></div></div>
                <div className="[word-break:break-word] content-stretch flex gap-[10px] items-center leading-[0] relative shrink-0 text-[12px] whitespace-nowrap"><div className="flex flex-col font-['Inter'] font-normal justify-center not-italic relative shrink-0 text-[#5f6368]"><p className="leading-[1.5]">TF-card &amp; cloud storage</p></div><div className="-translate-y-1/2 absolute flex flex-col font-['Manrope'] font-bold justify-center left-[-12px] text-[#fd022c] top-[8px]"><p className="leading-[16px]">&bull;</p></div></div>
                <div className="[word-break:break-word] content-stretch flex gap-[10px] items-center leading-[0] relative shrink-0 text-[12px] whitespace-nowrap"><div className="flex flex-col font-['Inter'] font-normal justify-center not-italic relative shrink-0 text-[#5f6368]"><p className="leading-[1.5]">Two-way audio</p></div><div className="-translate-y-1/2 absolute flex flex-col font-['Manrope'] font-bold justify-center left-[-12px] text-[#fd022c] top-[8px]"><p className="leading-[16px]">&bull;</p></div></div>
            </div>
            <div className="content-start flex flex-wrap gap-y-[8px] items-start relative shrink-0 w-full">
              <div className="content-stretch flex flex-col gap-[8px] items-start justify-center relative shrink-0">
                <div className="[word-break:break-word] flex flex-col font-['Inter'] font-normal justify-center leading-[0] not-italic relative shrink-0 text-[#111] text-[12px] whitespace-nowrap"><p className="leading-[1.5]">Use cases:</p></div>
                <div className="content-stretch flex gap-[8px] items-start relative shrink-0"><div className="[word-break:break-word] flex flex-col font-['Inter'] font-normal justify-center leading-[0] not-italic relative shrink-0 text-[#5f6368] text-[12px] whitespace-nowrap"><p className="leading-[1.5]">Remote Facilities</p></div><div className="[word-break:break-word] flex flex-col font-['Inter'] font-medium justify-center leading-[0] not-italic relative shrink-0 text-[#5f6368] text-[14px] whitespace-nowrap"><p className="leading-[1.2]">&middot;</p></div><div className="[word-break:break-word] flex flex-col font-['Inter'] font-normal justify-center leading-[0] not-italic relative shrink-0 text-[#5f6368] text-[12px] whitespace-nowrap"><p className="leading-[1.5]">Temporary Sites</p></div><div className="[word-break:break-word] flex flex-col font-['Inter'] font-medium justify-center leading-[0] not-italic relative shrink-0 text-[#5f6368] text-[14px] whitespace-nowrap"><p className="leading-[1.2]">&middot;</p></div><div className="[word-break:break-word] flex flex-col font-['Inter'] font-normal justify-center leading-[0] not-italic relative shrink-0 text-[#5f6368] text-[12px] whitespace-nowrap"><p className="leading-[1.5]">Field Locations</p></div></div>
              </div>
            </div>
          </div>
          <div className="bg-white drop-shadow-[0px_4px_10px_rgba(0,0,0,0.1)] flex h-[354px] items-start overflow-clip relative rounded-[24px] shrink-0 w-[515px]"><div className="flex-[1_0_0] h-full min-w-px relative"><img alt="HOUM camera" className="absolute inset-0 max-w-none object-cover pointer-events-none size-full" src={imgc9ae281a3c7c} /></div><div className="flex-[1_0_0] h-full min-w-px relative"><img alt="HOUM camera" className="absolute inset-0 max-w-none object-contain pointer-events-none size-full" src={imgabcfeca71284} /></div></div>
        </div>
        <div className="bg-white border border-[#e5e7eb] border-solid content-start drop-shadow-[0px_4px_10px_rgba(0,0,0,0.05)] flex flex-wrap gap-[48px] items-start justify-center p-[33px] relative rounded-[12px] shrink-0 w-full">
          <div className="bg-white drop-shadow-[0px_4px_10px_rgba(0,0,0,0.1)] flex h-[325px] items-start overflow-clip relative rounded-[24px] shrink-0 w-[515px]"><div className="flex-[1_0_0] h-full min-w-px relative"><img alt="HOUM camera" className="absolute inset-0 max-w-none object-contain pointer-events-none size-full" src={img2698b75cd3b1} /></div><div className="flex-[1_0_0] h-full min-w-px relative"><img alt="HOUM camera" className="absolute inset-0 max-w-none object-contain pointer-events-none size-full" src={img3544372595cc} /></div></div>
          <div className="content-stretch flex flex-col gap-[16px] items-start relative shrink-0 w-[556px]">
            <div className="content-stretch flex flex-col gap-[8px] items-start relative shrink-0 w-full">
              <div className="[word-break:break-word] flex flex-col font-['Inter'] font-bold justify-center leading-[0] not-italic relative shrink-0 text-[#fd022c] text-[14px] tracking-[1.4px] uppercase w-full"><p className="leading-[20px]">05 &mdash; Battery &amp; Solar Surveillance</p></div>
              <div className="[word-break:break-word] flex flex-col font-['Poppins'] justify-center leading-[0] not-italic relative shrink-0 text-[#111] text-[24px] w-full"><h3 className="leading-[1.2]">Flexible monitoring with independent power</h3></div>
            </div>
            <div className="[word-break:break-word] content-stretch flex flex-col font-['Inter'] font-normal gap-[8px] items-start leading-[0] not-italic relative shrink-0 w-full">
              <div className="content-stretch flex flex-col gap-[4px] items-start relative shrink-0 w-full">
                <div className="flex flex-col justify-center relative shrink-0 text-[#111] text-[16px] w-full"><p className="leading-[1.5]">HOUM-CB5 / HOUM-B01S / HOUM-R05 / HOUM-170S</p></div>
                <div className="flex flex-col justify-center relative shrink-0 text-[#3f4347] text-[14px] w-full"><p className="font-['Inter'] italic leading-[20px] text-[14px]">Battery &amp; Solar Camera Solutions</p></div>
              </div>
            </div>
            <div className="content-stretch flex flex-col gap-[4px] items-start pl-[16px] relative shrink-0 w-full">
                <div className="[word-break:break-word] content-stretch flex gap-[10px] items-center leading-[0] relative shrink-0 text-[12px] whitespace-nowrap"><div className="flex flex-col font-['Inter'] font-normal justify-center not-italic relative shrink-0 text-[#5f6368]"><p className="leading-[1.5]">Rechargeable battery</p></div><div className="-translate-y-1/2 absolute flex flex-col font-['Manrope'] font-bold justify-center left-[-12px] text-[#fd022c] top-[8px]"><p className="leading-[16px]">&bull;</p></div></div>
                <div className="[word-break:break-word] content-stretch flex gap-[10px] items-center leading-[0] relative shrink-0 text-[12px] whitespace-nowrap"><div className="flex flex-col font-['Inter'] font-normal justify-center not-italic relative shrink-0 text-[#5f6368]"><p className="leading-[1.5]">PIR motion detection</p></div><div className="-translate-y-1/2 absolute flex flex-col font-['Manrope'] font-bold justify-center left-[-12px] text-[#fd022c] top-[8px]"><p className="leading-[16px]">&bull;</p></div></div>
                <div className="[word-break:break-word] content-stretch flex gap-[10px] items-center leading-[0] relative shrink-0 text-[12px] whitespace-nowrap"><div className="flex flex-col font-['Inter'] font-normal justify-center not-italic relative shrink-0 text-[#5f6368]"><p className="leading-[1.5]">Wireless connectivity</p></div><div className="-translate-y-1/2 absolute flex flex-col font-['Manrope'] font-bold justify-center left-[-12px] text-[#fd022c] top-[8px]"><p className="leading-[16px]">&bull;</p></div></div>
                <div className="[word-break:break-word] content-stretch flex gap-[10px] items-center leading-[0] relative shrink-0 text-[12px] whitespace-nowrap"><div className="flex flex-col font-['Inter'] font-normal justify-center not-italic relative shrink-0 text-[#5f6368]"><p className="leading-[1.5]">Remote viewing</p></div><div className="-translate-y-1/2 absolute flex flex-col font-['Manrope'] font-bold justify-center left-[-12px] text-[#fd022c] top-[8px]"><p className="leading-[16px]">&bull;</p></div></div>
                <div className="[word-break:break-word] content-stretch flex gap-[10px] items-center leading-[0] relative shrink-0 text-[12px] whitespace-nowrap"><div className="flex flex-col font-['Inter'] font-normal justify-center not-italic relative shrink-0 text-[#5f6368]"><p className="leading-[1.5]">Local &amp; cloud storage</p></div><div className="-translate-y-1/2 absolute flex flex-col font-['Manrope'] font-bold justify-center left-[-12px] text-[#fd022c] top-[8px]"><p className="leading-[16px]">&bull;</p></div></div>
                <div className="[word-break:break-word] content-stretch flex gap-[10px] items-center leading-[0] relative shrink-0 text-[12px] whitespace-nowrap"><div className="flex flex-col font-['Inter'] font-normal justify-center not-italic relative shrink-0 text-[#5f6368]"><p className="leading-[1.5]">Solar panel options</p></div><div className="-translate-y-1/2 absolute flex flex-col font-['Manrope'] font-bold justify-center left-[-12px] text-[#fd022c] top-[8px]"><p className="leading-[16px]">&bull;</p></div></div>
            </div>
            <div className="content-start flex flex-wrap gap-y-[8px] items-start relative shrink-0 w-full">
              <div className="content-stretch flex flex-col gap-[8px] items-start justify-center relative shrink-0">
                <div className="[word-break:break-word] flex flex-col font-['Inter'] font-normal justify-center leading-[0] not-italic relative shrink-0 text-[#111] text-[12px] whitespace-nowrap"><p className="leading-[1.5]">Use cases:</p></div>
                <div className="content-stretch flex gap-[8px] items-start relative shrink-0"><div className="[word-break:break-word] flex flex-col font-['Inter'] font-normal justify-center leading-[0] not-italic relative shrink-0 text-[#5f6368] text-[12px] whitespace-nowrap"><p className="leading-[1.5]">Remote Areas</p></div><div className="[word-break:break-word] flex flex-col font-['Inter'] font-medium justify-center leading-[0] not-italic relative shrink-0 text-[#5f6368] text-[14px] whitespace-nowrap"><p className="leading-[1.2]">&middot;</p></div><div className="[word-break:break-word] flex flex-col font-['Inter'] font-normal justify-center leading-[0] not-italic relative shrink-0 text-[#5f6368] text-[12px] whitespace-nowrap"><p className="leading-[1.5]">Temporary Sites</p></div><div className="[word-break:break-word] flex flex-col font-['Inter'] font-medium justify-center leading-[0] not-italic relative shrink-0 text-[#5f6368] text-[14px] whitespace-nowrap"><p className="leading-[1.2]">&middot;</p></div><div className="[word-break:break-word] flex flex-col font-['Inter'] font-normal justify-center leading-[0] not-italic relative shrink-0 text-[#5f6368] text-[12px] whitespace-nowrap"><p className="leading-[1.5]">Low-Power Locations</p></div><div className="[word-break:break-word] flex flex-col font-['Inter'] font-medium justify-center leading-[0] not-italic relative shrink-0 text-[#5f6368] text-[14px] whitespace-nowrap"><p className="leading-[1.2]">&middot;</p></div><div className="[word-break:break-word] flex flex-col font-['Inter'] font-normal justify-center leading-[0] not-italic relative shrink-0 text-[#5f6368] text-[12px] whitespace-nowrap"><p className="leading-[1.5]">Outdoor Storage</p></div></div>
              </div>
            </div>
          </div>
        </div>
          </div>
        </div>
      </div>
    </>
  );
}
