import img1f5b5c863b36 from '@/assets/1f5b5c863b36.webp';
import imgf39a2dd5ab10 from '@/assets/f39a2dd5ab10.webp';
import imgacad6eb87684 from '@/assets/acad6eb87684.webp';
import imge81b39f42ea2 from '@/assets/e81b39f42ea2.webp';
import img199ef5aaa5b0 from '@/assets/199ef5aaa5b0.webp';
import imgcf14b3085176 from '@/assets/cf14b3085176.webp';

export default function SolutionSection() {
  return (
    <>
      <div className="bg-[#fff1f2] pt-[72px] px-[72px] relative size-full">
      <div className="content-stretch flex flex-col gap-[80px] items-center relative w-full">
        <div className="content-stretch flex flex-col gap-[16px] items-start justify-end relative shrink-0 w-full">
          <div className="content-stretch flex flex-col gap-[8px] items-start relative shrink-0 w-full">
            <div className="content-stretch flex items-center justify-center relative shrink-0 w-full"><div className="[word-break:break-word] flex flex-col font-['Inter'] font-bold justify-center leading-[0] not-italic relative shrink-0 text-[#fd022c] text-[14px] text-center tracking-[1.4px] uppercase whitespace-nowrap"><p className="leading-[20px]">HOUM Solution</p></div></div>
            <div className="content-stretch flex flex-col items-center justify-center relative shrink-0 w-full"><div className="[word-break:break-word] flex flex-col font-['Roboto'] font-semibold justify-center leading-[0] relative shrink-0 text-[#111] text-[32px] text-center w-full" style={{ fontVariationSettings: "'wdth' 100" }}><h2 className="leading-[1.2]">One Security Ecosystem.<br />Every Critical Asset</h2></div></div>
          </div>
          <div className="content-stretch flex flex-col items-center justify-center relative shrink-0 w-full"><div className="[word-break:break-word] flex flex-col font-['Inter'] font-normal justify-center leading-[0] max-w-[477px] not-italic relative shrink-0 text-[#111] text-[16px] text-center w-full"><p className="leading-[1.5]">HOUM connects video surveillance, AI analytics, thermal intelligence, access control, mobile monitoring, and command &amp; control into a unified security environment.</p></div></div>
        </div>
        <div className="content-center flex flex-wrap gap-[24px] items-center relative shrink-0 w-full">
          <div className="bg-[#3f4347] flex-[1_0_0] h-[448px] min-w-[416px] overflow-clip relative rounded-[24px] shadow-[0px_25px_50px_-12px_rgba(0,0,0,0.25)]"><div className="absolute inset-0 overflow-hidden pointer-events-none"><img alt="Store entrance" className="absolute h-[208.64%] left-0 max-w-none top-[-81.71%] w-full" src={img1f5b5c863b36} /></div></div>
          <div className="bg-white border border-[#e5e5e5] border-solid content-stretch flex flex-[1_0_0] flex-col gap-[16px] items-start justify-center min-w-[416px] p-[40px] relative rounded-[24px]">
            <div className="content-stretch flex flex-col gap-[8px] items-start relative shrink-0 w-full">
              <div className="[word-break:break-word] flex flex-col font-['Inter'] font-bold justify-center leading-[0] not-italic relative shrink-0 text-[#fd022c] text-[14px] tracking-[1.4px] uppercase w-full"><p className="leading-[20px]">01 &mdash; STORE ENTRANCE</p></div>
              <div className="[word-break:break-word] flex flex-col font-['Poppins'] justify-center leading-[0] not-italic relative shrink-0 text-[#111] text-[24px] w-full"><h3 className="leading-[1.2]">Clear Visibility at Every Entry Point</h3></div>
            </div>
            <div className="[word-break:break-word] content-stretch flex flex-col font-['Inter'] font-normal gap-[8px] items-start leading-[0] not-italic pt-[8px] relative shrink-0 w-full">
              <div className="[word-break:break-word] flex flex-col justify-center relative shrink-0 text-[#5f6368] text-[16px] w-full"><p className="leading-[1.5]">Monitor entrances and access areas with high-resolution outdoor surveillance and night vision.</p></div>
              <div className="content-stretch flex flex-col gap-[4px] items-start relative shrink-0 w-full">
                <div className="flex flex-col justify-center relative shrink-0 text-[#111] text-[16px] w-full"><p className="leading-[1.5]">HOUM-K233</p></div>
                <div className="flex flex-col justify-center relative shrink-0 text-[#3f4347] text-[14px] w-full"><p className="font-['Inter'] italic leading-[20px] text-[14px]">Outdoor Bullet Camera</p></div>
              </div>
            </div>
            <div className="content-stretch flex flex-col gap-[4px] items-start pl-[16px] relative shrink-0 w-full">
                <div className="[word-break:break-word] content-stretch flex gap-[10px] items-center leading-[0] relative shrink-0 text-[12px] whitespace-nowrap"><div className="flex flex-col font-['Inter'] font-normal justify-center not-italic relative shrink-0 text-[#5f6368]"><p className="leading-[1.5]">2MP Full HD video</p></div><div className="-translate-y-1/2 absolute flex flex-col font-['Manrope'] font-bold justify-center left-[-12px] text-[#fd022c] top-[8px]"><p className="leading-[16px]">&bull;</p></div></div>
                <div className="[word-break:break-word] content-stretch flex gap-[10px] items-center leading-[0] relative shrink-0 text-[12px] whitespace-nowrap"><div className="flex flex-col font-['Inter'] font-normal justify-center not-italic relative shrink-0 text-[#5f6368]"><p className="leading-[1.5]">Wide viewing angle</p></div><div className="-translate-y-1/2 absolute flex flex-col font-['Manrope'] font-bold justify-center left-[-12px] text-[#fd022c] top-[8px]"><p className="leading-[16px]">&bull;</p></div></div>
                <div className="[word-break:break-word] content-stretch flex gap-[10px] items-center leading-[0] relative shrink-0 text-[12px] whitespace-nowrap"><div className="flex flex-col font-['Inter'] font-normal justify-center not-italic relative shrink-0 text-[#5f6368]"><p className="leading-[1.5]">Motion detection</p></div><div className="-translate-y-1/2 absolute flex flex-col font-['Manrope'] font-bold justify-center left-[-12px] text-[#fd022c] top-[8px]"><p className="leading-[16px]">&bull;</p></div></div>
                <div className="[word-break:break-word] content-stretch flex gap-[10px] items-center leading-[0] relative shrink-0 text-[12px] whitespace-nowrap"><div className="flex flex-col font-['Inter'] font-normal justify-center not-italic relative shrink-0 text-[#5f6368]"><p className="leading-[1.5]">Up to 15m IR night vision</p></div><div className="-translate-y-1/2 absolute flex flex-col font-['Manrope'] font-bold justify-center left-[-12px] text-[#fd022c] top-[8px]"><p className="leading-[16px]">&bull;</p></div></div>
                <div className="[word-break:break-word] content-stretch flex gap-[10px] items-center leading-[0] relative shrink-0 text-[12px] whitespace-nowrap"><div className="flex flex-col font-['Inter'] font-normal justify-center not-italic relative shrink-0 text-[#5f6368]"><p className="leading-[1.5]">Two-way audio</p></div><div className="-translate-y-1/2 absolute flex flex-col font-['Manrope'] font-bold justify-center left-[-12px] text-[#fd022c] top-[8px]"><p className="leading-[16px]">&bull;</p></div></div>
                <div className="[word-break:break-word] content-stretch flex gap-[10px] items-center leading-[0] relative shrink-0 text-[12px] whitespace-nowrap"><div className="flex flex-col font-['Inter'] font-normal justify-center not-italic relative shrink-0 text-[#5f6368]"><p className="leading-[1.5]">Remote viewing &amp; control</p></div><div className="-translate-y-1/2 absolute flex flex-col font-['Manrope'] font-bold justify-center left-[-12px] text-[#fd022c] top-[8px]"><p className="leading-[16px]">&bull;</p></div></div>
            </div>
            <div className="content-start flex flex-wrap gap-y-[8px] items-start relative shrink-0 w-full">
              <div className="content-stretch flex flex-col gap-[8px] items-start justify-center relative shrink-0">
                <div className="[word-break:break-word] flex flex-col font-['Inter'] font-normal justify-center leading-[0] not-italic relative shrink-0 text-[#111] text-[12px] whitespace-nowrap"><p className="leading-[1.5]">Use cases:</p></div>
                <div className="content-stretch flex gap-[8px] items-start relative shrink-0"><div className="[word-break:break-word] flex flex-col font-['Inter'] font-normal justify-center leading-[0] not-italic relative shrink-0 text-[#5f6368] text-[12px] whitespace-nowrap"><p className="leading-[1.5]">Store Entrances</p></div><div className="[word-break:break-word] flex flex-col font-['Inter'] font-medium justify-center leading-[0] not-italic relative shrink-0 text-[#5f6368] text-[14px] whitespace-nowrap"><p className="leading-[1.2]">&middot;</p></div><div className="[word-break:break-word] flex flex-col font-['Inter'] font-normal justify-center leading-[0] not-italic relative shrink-0 text-[#5f6368] text-[12px] whitespace-nowrap"><p className="leading-[1.5]">Entry Points</p></div><div className="[word-break:break-word] flex flex-col font-['Inter'] font-medium justify-center leading-[0] not-italic relative shrink-0 text-[#5f6368] text-[14px] whitespace-nowrap"><p className="leading-[1.2]">&middot;</p></div><div className="[word-break:break-word] flex flex-col font-['Inter'] font-normal justify-center leading-[0] not-italic relative shrink-0 text-[#5f6368] text-[12px] whitespace-nowrap"><p className="leading-[1.5]">Exterior Areas</p></div></div>
              </div>
            </div>
          </div>
        </div>
        <div className="content-center flex flex-wrap gap-[24px] items-center relative shrink-0 w-full">
          <div className="bg-white border border-[#e5e5e5] border-solid content-stretch flex flex-[1_0_0] flex-col gap-[16px] items-start justify-center min-w-[416px] p-[40px] relative rounded-[24px]">
            <div className="content-stretch flex flex-col gap-[8px] items-start relative shrink-0 w-full">
              <div className="[word-break:break-word] flex flex-col font-['Inter'] font-bold justify-center leading-[0] not-italic relative shrink-0 text-[#fd022c] text-[14px] tracking-[1.4px] uppercase w-full"><p className="leading-[20px]">02 &mdash; SHOP FLOOR</p></div>
              <div className="[word-break:break-word] flex flex-col font-['Poppins'] justify-center leading-[0] not-italic relative shrink-0 text-[#111] text-[24px] w-full"><h3 className="leading-[1.2]">Smarter Monitoring Across the Store</h3></div>
            </div>
            <div className="[word-break:break-word] content-stretch flex flex-col font-['Inter'] font-normal gap-[8px] items-start leading-[0] not-italic pt-[8px] relative shrink-0 w-full">
              <div className="[word-break:break-word] flex flex-col justify-center relative shrink-0 text-[#5f6368] text-[16px] w-full"><p className="leading-[1.5]">Cover aisles, displays and customer areas with PT cameras featuring wide coverage and moving tracking.</p></div>
              <div className="content-stretch flex flex-col gap-[4px] items-start relative shrink-0 w-full">
                <div className="flex flex-col justify-center relative shrink-0 text-[#111] text-[16px] w-full"><p className="leading-[1.5]">HOUM-P158 / HOUM-P161 / HOUM-P162 / HOUM-P163</p></div>
                <div className="flex flex-col justify-center relative shrink-0 text-[#3f4347] text-[14px] w-full"><p className="font-['Inter'] italic leading-[20px] text-[14px]">Smart PT Indoor Camera</p></div>
              </div>
            </div>
            <div className="content-stretch flex flex-col gap-[4px] items-start pl-[16px] relative shrink-0 w-full">
                <div className="[word-break:break-word] content-stretch flex gap-[10px] items-center leading-[0] relative shrink-0 text-[12px] whitespace-nowrap"><div className="flex flex-col font-['Inter'] font-normal justify-center not-italic relative shrink-0 text-[#5f6368]"><p className="leading-[1.5]">Up to 5MP resolution</p></div><div className="-translate-y-1/2 absolute flex flex-col font-['Manrope'] font-bold justify-center left-[-12px] text-[#fd022c] top-[8px]"><p className="leading-[16px]">&bull;</p></div></div>
                <div className="[word-break:break-word] content-stretch flex gap-[10px] items-center leading-[0] relative shrink-0 text-[12px] whitespace-nowrap"><div className="flex flex-col font-['Inter'] font-normal justify-center not-italic relative shrink-0 text-[#5f6368]"><p className="leading-[1.5]">355&deg; horizontal coverage</p></div><div className="-translate-y-1/2 absolute flex flex-col font-['Manrope'] font-bold justify-center left-[-12px] text-[#fd022c] top-[8px]"><p className="leading-[16px]">&bull;</p></div></div>
                <div className="[word-break:break-word] content-stretch flex gap-[10px] items-center leading-[0] relative shrink-0 text-[12px] whitespace-nowrap"><div className="flex flex-col font-['Inter'] font-normal justify-center not-italic relative shrink-0 text-[#5f6368]"><p className="leading-[1.5]">Motion detection</p></div><div className="-translate-y-1/2 absolute flex flex-col font-['Manrope'] font-bold justify-center left-[-12px] text-[#fd022c] top-[8px]"><p className="leading-[16px]">&bull;</p></div></div>
                <div className="[word-break:break-word] content-stretch flex gap-[10px] items-center leading-[0] relative shrink-0 text-[12px] whitespace-nowrap"><div className="flex flex-col font-['Inter'] font-normal justify-center not-italic relative shrink-0 text-[#5f6368]"><p className="leading-[1.5]">Day/night IR vision</p></div><div className="-translate-y-1/2 absolute flex flex-col font-['Manrope'] font-bold justify-center left-[-12px] text-[#fd022c] top-[8px]"><p className="leading-[16px]">&bull;</p></div></div>
                <div className="[word-break:break-word] content-stretch flex gap-[10px] items-center leading-[0] relative shrink-0 text-[12px] whitespace-nowrap"><div className="flex flex-col font-['Inter'] font-normal justify-center not-italic relative shrink-0 text-[#5f6368]"><p className="leading-[1.5]">Two-way audio</p></div><div className="-translate-y-1/2 absolute flex flex-col font-['Manrope'] font-bold justify-center left-[-12px] text-[#fd022c] top-[8px]"><p className="leading-[16px]">&bull;</p></div></div>
                <div className="[word-break:break-word] content-stretch flex gap-[10px] items-center leading-[0] relative shrink-0 text-[12px] whitespace-nowrap"><div className="flex flex-col font-['Inter'] font-normal justify-center not-italic relative shrink-0 text-[#5f6368]"><p className="leading-[1.5]">Moving tracking</p></div><div className="-translate-y-1/2 absolute flex flex-col font-['Manrope'] font-bold justify-center left-[-12px] text-[#fd022c] top-[8px]"><p className="leading-[16px]">&bull;</p></div></div>
            </div>
            <div className="content-start flex flex-wrap gap-y-[8px] items-start relative shrink-0 w-full">
              <div className="content-stretch flex flex-col gap-[8px] items-start justify-center relative shrink-0">
                <div className="[word-break:break-word] flex flex-col font-['Inter'] font-normal justify-center leading-[0] not-italic relative shrink-0 text-[#111] text-[12px] whitespace-nowrap"><p className="leading-[1.5]">Use cases:</p></div>
                <div className="content-stretch flex gap-[8px] items-start relative shrink-0"><div className="[word-break:break-word] flex flex-col font-['Inter'] font-normal justify-center leading-[0] not-italic relative shrink-0 text-[#5f6368] text-[12px] whitespace-nowrap"><p className="leading-[1.5]">Sales Floors</p></div><div className="[word-break:break-word] flex flex-col font-['Inter'] font-medium justify-center leading-[0] not-italic relative shrink-0 text-[#5f6368] text-[14px] whitespace-nowrap"><p className="leading-[1.2]">&middot;</p></div><div className="[word-break:break-word] flex flex-col font-['Inter'] font-normal justify-center leading-[0] not-italic relative shrink-0 text-[#5f6368] text-[12px] whitespace-nowrap"><p className="leading-[1.5]">Aisles</p></div><div className="[word-break:break-word] flex flex-col font-['Inter'] font-medium justify-center leading-[0] not-italic relative shrink-0 text-[#5f6368] text-[14px] whitespace-nowrap"><p className="leading-[1.2]">&middot;</p></div><div className="[word-break:break-word] flex flex-col font-['Inter'] font-normal justify-center leading-[0] not-italic relative shrink-0 text-[#5f6368] text-[12px] whitespace-nowrap"><p className="leading-[1.5]">Display Areas</p></div><div className="[word-break:break-word] flex flex-col font-['Inter'] font-medium justify-center leading-[0] not-italic relative shrink-0 text-[#5f6368] text-[14px] whitespace-nowrap"><p className="leading-[1.2]">&middot;</p></div><div className="[word-break:break-word] flex flex-col font-['Inter'] font-normal justify-center leading-[0] not-italic relative shrink-0 text-[#5f6368] text-[12px] whitespace-nowrap"><p className="leading-[1.5]">Customer Zones</p></div></div>
              </div>
            </div>
          </div>
          <div className="bg-[#3f4347] flex-[1_0_0] h-[448px] min-w-[416px] overflow-clip relative rounded-[24px] shadow-[0px_25px_50px_-12px_rgba(0,0,0,0.25)]"><div className="absolute inset-0 overflow-hidden pointer-events-none"><img alt="Supermarket aisle" className="absolute inset-0 max-w-none object-cover size-full" src={imgf39a2dd5ab10} /></div></div>
        </div>
        <div className="content-center flex flex-wrap gap-[24px] items-center relative shrink-0 w-full">
          <div className="bg-[#3f4347] flex-[1_0_0] h-[448px] min-w-[416px] overflow-clip relative rounded-[24px] shadow-[0px_25px_50px_-12px_rgba(0,0,0,0.25)]"><div className="absolute inset-0 overflow-hidden pointer-events-none"><img alt="Parking garage" className="absolute inset-0 max-w-none object-cover size-full" src={imgacad6eb87684} /></div></div>
          <div className="bg-white border border-[#e5e5e5] border-solid content-stretch flex flex-[1_0_0] flex-col gap-[16px] items-start justify-center min-w-[416px] p-[40px] relative rounded-[24px]">
            <div className="content-stretch flex flex-col gap-[8px] items-start relative shrink-0 w-full">
              <div className="[word-break:break-word] flex flex-col font-['Inter'] font-bold justify-center leading-[0] not-italic relative shrink-0 text-[#fd022c] text-[14px] tracking-[1.4px] uppercase w-full"><p className="leading-[20px]">03 &mdash; PARKING &amp; OUTDOOR AREAS</p></div>
              <div className="[word-break:break-word] flex flex-col font-['Poppins'] justify-center leading-[0] not-italic relative shrink-0 text-[#111] text-[24px] w-full"><h3 className="leading-[1.2]">Wide-Area Outdoor Monitoring</h3></div>
            </div>
            <div className="[word-break:break-word] content-stretch flex flex-col font-['Inter'] font-normal gap-[8px] items-start leading-[0] not-italic pt-[8px] relative shrink-0 w-full">
              <div className="[word-break:break-word] flex flex-col justify-center relative shrink-0 text-[#5f6368] text-[16px] w-full"><p className="leading-[1.5]">Monitor parking and outdoor spaces with auto-tracking cameras and intelligent area detection.</p></div>
              <div className="content-stretch flex flex-col gap-[4px] items-start relative shrink-0 w-full">
                <div className="flex flex-col justify-center relative shrink-0 text-[#111] text-[16px] w-full"><p className="leading-[1.5]">HOUM-PL01</p></div>
                <div className="flex flex-col justify-center relative shrink-0 text-[#3f4347] text-[14px] w-full"><p className="font-['Inter'] italic leading-[20px] text-[14px]">4MP Outdoor Lantern Camera</p></div>
              </div>
            </div>
            <div className="content-stretch flex flex-col gap-[4px] items-start pl-[16px] relative shrink-0 w-full">
                <div className="[word-break:break-word] content-stretch flex gap-[10px] items-center leading-[0] relative shrink-0 text-[12px] whitespace-nowrap"><div className="flex flex-col font-['Inter'] font-normal justify-center not-italic relative shrink-0 text-[#5f6368]"><p className="leading-[1.5]">4MP high-resolution video</p></div><div className="-translate-y-1/2 absolute flex flex-col font-['Manrope'] font-bold justify-center left-[-12px] text-[#fd022c] top-[8px]"><p className="leading-[16px]">&bull;</p></div></div>
                <div className="[word-break:break-word] content-stretch flex gap-[10px] items-center leading-[0] relative shrink-0 text-[12px] whitespace-nowrap"><div className="flex flex-col font-['Inter'] font-normal justify-center not-italic relative shrink-0 text-[#5f6368]"><p className="leading-[1.5]">Auto-tracking</p></div><div className="-translate-y-1/2 absolute flex flex-col font-['Manrope'] font-bold justify-center left-[-12px] text-[#fd022c] top-[8px]"><p className="leading-[16px]">&bull;</p></div></div>
                <div className="[word-break:break-word] content-stretch flex gap-[10px] items-center leading-[0] relative shrink-0 text-[12px] whitespace-nowrap"><div className="flex flex-col font-['Inter'] font-normal justify-center not-italic relative shrink-0 text-[#5f6368]"><p className="leading-[1.5]">Motion detection</p></div><div className="-translate-y-1/2 absolute flex flex-col font-['Manrope'] font-bold justify-center left-[-12px] text-[#fd022c] top-[8px]"><p className="leading-[16px]">&bull;</p></div></div>
                <div className="[word-break:break-word] content-stretch flex gap-[10px] items-center leading-[0] relative shrink-0 text-[12px] whitespace-nowrap"><div className="flex flex-col font-['Inter'] font-normal justify-center not-italic relative shrink-0 text-[#5f6368]"><p className="leading-[1.5]">Object outline &amp; area detection</p></div><div className="-translate-y-1/2 absolute flex flex-col font-['Manrope'] font-bold justify-center left-[-12px] text-[#fd022c] top-[8px]"><p className="leading-[16px]">&bull;</p></div></div>
                <div className="[word-break:break-word] content-stretch flex gap-[10px] items-center leading-[0] relative shrink-0 text-[12px] whitespace-nowrap"><div className="flex flex-col font-['Inter'] font-normal justify-center not-italic relative shrink-0 text-[#5f6368]"><p className="leading-[1.5]">ONVIF support</p></div><div className="-translate-y-1/2 absolute flex flex-col font-['Manrope'] font-bold justify-center left-[-12px] text-[#fd022c] top-[8px]"><p className="leading-[16px]">&bull;</p></div></div>
                <div className="[word-break:break-word] content-stretch flex gap-[10px] items-center leading-[0] relative shrink-0 text-[12px] whitespace-nowrap"><div className="flex flex-col font-['Inter'] font-normal justify-center not-italic relative shrink-0 text-[#5f6368]"><p className="leading-[1.5]">IP65 outdoor protection</p></div><div className="-translate-y-1/2 absolute flex flex-col font-['Manrope'] font-bold justify-center left-[-12px] text-[#fd022c] top-[8px]"><p className="leading-[16px]">&bull;</p></div></div>
            </div>
            <div className="content-start flex flex-wrap gap-y-[8px] items-start relative shrink-0 w-full">
              <div className="content-stretch flex flex-col gap-[8px] items-start justify-center relative shrink-0">
                <div className="[word-break:break-word] flex flex-col font-['Inter'] font-normal justify-center leading-[0] not-italic relative shrink-0 text-[#111] text-[12px] whitespace-nowrap"><p className="leading-[1.5]">Use cases:</p></div>
                <div className="content-stretch flex gap-[8px] items-start relative shrink-0"><div className="[word-break:break-word] flex flex-col font-['Inter'] font-normal justify-center leading-[0] not-italic relative shrink-0 text-[#5f6368] text-[12px] whitespace-nowrap"><p className="leading-[1.5]">Parking Areas</p></div><div className="[word-break:break-word] flex flex-col font-['Inter'] font-medium justify-center leading-[0] not-italic relative shrink-0 text-[#5f6368] text-[14px] whitespace-nowrap"><p className="leading-[1.2]">&middot;</p></div><div className="[word-break:break-word] flex flex-col font-['Inter'] font-normal justify-center leading-[0] not-italic relative shrink-0 text-[#5f6368] text-[12px] whitespace-nowrap"><p className="leading-[1.5]">Store Perimeters</p></div><div className="[word-break:break-word] flex flex-col font-['Inter'] font-medium justify-center leading-[0] not-italic relative shrink-0 text-[#5f6368] text-[14px] whitespace-nowrap"><p className="leading-[1.2]">&middot;</p></div><div className="[word-break:break-word] flex flex-col font-['Inter'] font-normal justify-center leading-[0] not-italic relative shrink-0 text-[#5f6368] text-[12px] whitespace-nowrap"><p className="leading-[1.5]">Outdoor Zones</p></div></div>
              </div>
            </div>
          </div>
        </div>
        <div className="content-center flex flex-wrap gap-[24px] items-center relative shrink-0 w-full">
          <div className="bg-white border border-[#e5e5e5] border-solid content-stretch flex flex-[1_0_0] flex-col gap-[16px] items-start justify-center min-w-[416px] p-[40px] relative rounded-[24px]">
            <div className="content-stretch flex flex-col gap-[8px] items-start relative shrink-0 w-full">
              <div className="[word-break:break-word] flex flex-col font-['Inter'] font-bold justify-center leading-[0] not-italic relative shrink-0 text-[#fd022c] text-[14px] tracking-[1.4px] uppercase w-full"><p className="leading-[20px]">04 &mdash; STORE PERIMETER</p></div>
              <div className="[word-break:break-word] flex flex-col font-['Poppins'] justify-center leading-[0] not-italic relative shrink-0 text-[#111] text-[24px] w-full"><h3 className="leading-[1.2]">Protection Beyond the Store</h3></div>
            </div>
            <div className="[word-break:break-word] content-stretch flex flex-col font-['Inter'] font-normal gap-[8px] items-start leading-[0] not-italic pt-[8px] relative shrink-0 w-full">
              <div className="[word-break:break-word] flex flex-col justify-center relative shrink-0 text-[#5f6368] text-[16px] w-full"><p className="leading-[1.5]">Keep perimeters, loading areas and external entrances under continuous outdoor surveillance.</p></div>
              <div className="content-stretch flex flex-col gap-[4px] items-start relative shrink-0 w-full">
                <div className="flex flex-col justify-center relative shrink-0 text-[#111] text-[16px] w-full"><p className="leading-[1.5]">HOUM-GL09</p></div>
                <div className="flex flex-col justify-center relative shrink-0 text-[#3f4347] text-[14px] w-full"><p className="font-['Inter'] italic leading-[20px] text-[14px]">4MP Outdoor Floodlight Camera</p></div>
              </div>
            </div>
            <div className="content-stretch flex flex-col gap-[4px] items-start pl-[16px] relative shrink-0 w-full">
                <div className="[word-break:break-word] content-stretch flex gap-[10px] items-center leading-[0] relative shrink-0 text-[12px] whitespace-nowrap"><div className="flex flex-col font-['Inter'] font-normal justify-center not-italic relative shrink-0 text-[#5f6368]"><p className="leading-[1.5]">4MP resolution</p></div><div className="-translate-y-1/2 absolute flex flex-col font-['Manrope'] font-bold justify-center left-[-12px] text-[#fd022c] top-[8px]"><p className="leading-[16px]">&bull;</p></div></div>
                <div className="[word-break:break-word] content-stretch flex gap-[10px] items-center leading-[0] relative shrink-0 text-[12px] whitespace-nowrap"><div className="flex flex-col font-['Inter'] font-normal justify-center not-italic relative shrink-0 text-[#5f6368]"><p className="leading-[1.5]">355&deg; rotation</p></div><div className="-translate-y-1/2 absolute flex flex-col font-['Manrope'] font-bold justify-center left-[-12px] text-[#fd022c] top-[8px]"><p className="leading-[16px]">&bull;</p></div></div>
                <div className="[word-break:break-word] content-stretch flex gap-[10px] items-center leading-[0] relative shrink-0 text-[12px] whitespace-nowrap"><div className="flex flex-col font-['Inter'] font-normal justify-center not-italic relative shrink-0 text-[#5f6368]"><p className="leading-[1.5]">180&deg; tilt</p></div><div className="-translate-y-1/2 absolute flex flex-col font-['Manrope'] font-bold justify-center left-[-12px] text-[#fd022c] top-[8px]"><p className="leading-[16px]">&bull;</p></div></div>
                <div className="[word-break:break-word] content-stretch flex gap-[10px] items-center leading-[0] relative shrink-0 text-[12px] whitespace-nowrap"><div className="flex flex-col font-['Inter'] font-normal justify-center not-italic relative shrink-0 text-[#5f6368]"><p className="leading-[1.5]">Auto-tracking</p></div><div className="-translate-y-1/2 absolute flex flex-col font-['Manrope'] font-bold justify-center left-[-12px] text-[#fd022c] top-[8px]"><p className="leading-[16px]">&bull;</p></div></div>
                <div className="[word-break:break-word] content-stretch flex gap-[10px] items-center leading-[0] relative shrink-0 text-[12px] whitespace-nowrap"><div className="flex flex-col font-['Inter'] font-normal justify-center not-italic relative shrink-0 text-[#5f6368]"><p className="leading-[1.5]">Motion detection</p></div><div className="-translate-y-1/2 absolute flex flex-col font-['Manrope'] font-bold justify-center left-[-12px] text-[#fd022c] top-[8px]"><p className="leading-[16px]">&bull;</p></div></div>
                <div className="[word-break:break-word] content-stretch flex gap-[10px] items-center leading-[0] relative shrink-0 text-[12px] whitespace-nowrap"><div className="flex flex-col font-['Inter'] font-normal justify-center not-italic relative shrink-0 text-[#5f6368]"><p className="leading-[1.5]">IP65 outdoor protection</p></div><div className="-translate-y-1/2 absolute flex flex-col font-['Manrope'] font-bold justify-center left-[-12px] text-[#fd022c] top-[8px]"><p className="leading-[16px]">&bull;</p></div></div>
            </div>
            <div className="content-start flex flex-wrap gap-y-[8px] items-start relative shrink-0 w-full">
              <div className="content-stretch flex flex-col gap-[8px] items-start justify-center relative shrink-0">
                <div className="[word-break:break-word] flex flex-col font-['Inter'] font-normal justify-center leading-[0] not-italic relative shrink-0 text-[#111] text-[12px] whitespace-nowrap"><p className="leading-[1.5]">Use cases:</p></div>
                <div className="content-stretch flex gap-[8px] items-start relative shrink-0"><div className="[word-break:break-word] flex flex-col font-['Inter'] font-normal justify-center leading-[0] not-italic relative shrink-0 text-[#5f6368] text-[12px] whitespace-nowrap"><p className="leading-[1.5]">Perimeters</p></div><div className="[word-break:break-word] flex flex-col font-['Inter'] font-medium justify-center leading-[0] not-italic relative shrink-0 text-[#5f6368] text-[14px] whitespace-nowrap"><p className="leading-[1.2]">&middot;</p></div><div className="[word-break:break-word] flex flex-col font-['Inter'] font-normal justify-center leading-[0] not-italic relative shrink-0 text-[#5f6368] text-[12px] whitespace-nowrap"><p className="leading-[1.5]">Parking</p></div><div className="[word-break:break-word] flex flex-col font-['Inter'] font-medium justify-center leading-[0] not-italic relative shrink-0 text-[#5f6368] text-[14px] whitespace-nowrap"><p className="leading-[1.2]">&middot;</p></div><div className="[word-break:break-word] flex flex-col font-['Inter'] font-normal justify-center leading-[0] not-italic relative shrink-0 text-[#5f6368] text-[12px] whitespace-nowrap"><p className="leading-[1.5]">Loading Areas</p></div><div className="[word-break:break-word] flex flex-col font-['Inter'] font-medium justify-center leading-[0] not-italic relative shrink-0 text-[#5f6368] text-[14px] whitespace-nowrap"><p className="leading-[1.2]">&middot;</p></div><div className="[word-break:break-word] flex flex-col font-['Inter'] font-normal justify-center leading-[0] not-italic relative shrink-0 text-[#5f6368] text-[12px] whitespace-nowrap"><p className="leading-[1.5]">External Entrances</p></div></div>
              </div>
            </div>
          </div>
          <div className="bg-[#3f4347] flex-[1_0_0] h-[448px] min-w-[416px] overflow-clip relative rounded-[24px] shadow-[0px_25px_50px_-12px_rgba(0,0,0,0.25)]"><div className="absolute inset-0 overflow-hidden pointer-events-none"><img alt="Store exterior" className="absolute h-[252.16%] left-[-0.04%] max-w-none top-[-130.76%] w-full" src={imge81b39f42ea2} /></div></div>
        </div>
        <div className="content-center flex flex-wrap gap-[24px] items-center relative shrink-0 w-full">
          <div className="bg-[#3f4347] flex-[1_0_0] h-[448px] min-w-[416px] overflow-clip relative rounded-[24px] shadow-[0px_25px_50px_-12px_rgba(0,0,0,0.25)]"><div className="absolute inset-0 overflow-hidden pointer-events-none"><img alt="Remote retail site" className="absolute inset-0 max-w-none object-cover size-full" src={img199ef5aaa5b0} /></div></div>
          <div className="bg-white border border-[#e5e5e5] border-solid content-stretch flex flex-[1_0_0] flex-col gap-[16px] items-start justify-center min-w-[416px] p-[40px] relative rounded-[24px]">
            <div className="content-stretch flex flex-col gap-[8px] items-start relative shrink-0 w-full">
              <div className="[word-break:break-word] flex flex-col font-['Inter'] font-bold justify-center leading-[0] not-italic relative shrink-0 text-[#fd022c] text-[14px] tracking-[1.4px] uppercase w-full"><p className="leading-[20px]">05 &mdash; REMOTE &amp; LOW-POWER AREAS</p></div>
              <div className="[word-break:break-word] flex flex-col font-['Poppins'] justify-center leading-[0] not-italic relative shrink-0 text-[#111] text-[24px] w-full"><h3 className="leading-[1.2]">Flexible Security Where You Need It</h3></div>
            </div>
            <div className="[word-break:break-word] content-stretch flex flex-col font-['Inter'] font-normal gap-[8px] items-start leading-[0] not-italic pt-[8px] relative shrink-0 w-full">
              <div className="[word-break:break-word] flex flex-col justify-center relative shrink-0 text-[#5f6368] text-[16px] w-full"><p className="leading-[1.5]">Protect remote or low-power locations with battery-powered cameras and flexible solar options.</p></div>
              <div className="content-stretch flex flex-col gap-[4px] items-start relative shrink-0 w-full">
                <div className="flex flex-col justify-center relative shrink-0 text-[#111] text-[16px] w-full"><p className="leading-[1.5]">HOUM-CB5 / HOUM-170S</p></div>
                <div className="flex flex-col justify-center relative shrink-0 text-[#3f4347] text-[14px] w-full"><p className="font-['Inter'] italic leading-[20px] text-[14px]">Battery &amp; 4G Outdoor Cameras</p></div>
              </div>
            </div>
            <div className="content-stretch flex flex-col gap-[4px] items-start pl-[16px] relative shrink-0 w-full">
                <div className="[word-break:break-word] content-stretch flex gap-[10px] items-center leading-[0] relative shrink-0 text-[12px] whitespace-nowrap"><div className="flex flex-col font-['Inter'] font-normal justify-center not-italic relative shrink-0 text-[#5f6368]"><p className="leading-[1.5]">Battery-powered operation</p></div><div className="-translate-y-1/2 absolute flex flex-col font-['Manrope'] font-bold justify-center left-[-12px] text-[#fd022c] top-[8px]"><p className="leading-[16px]">&bull;</p></div></div>
                <div className="[word-break:break-word] content-stretch flex gap-[10px] items-center leading-[0] relative shrink-0 text-[12px] whitespace-nowrap"><div className="flex flex-col font-['Inter'] font-normal justify-center not-italic relative shrink-0 text-[#5f6368]"><p className="leading-[1.5]">PIR motion detection</p></div><div className="-translate-y-1/2 absolute flex flex-col font-['Manrope'] font-bold justify-center left-[-12px] text-[#fd022c] top-[8px]"><p className="leading-[16px]">&bull;</p></div></div>
                <div className="[word-break:break-word] content-stretch flex gap-[10px] items-center leading-[0] relative shrink-0 text-[12px] whitespace-nowrap"><div className="flex flex-col font-['Inter'] font-normal justify-center not-italic relative shrink-0 text-[#5f6368]"><p className="leading-[1.5]">Two-way audio</p></div><div className="-translate-y-1/2 absolute flex flex-col font-['Manrope'] font-bold justify-center left-[-12px] text-[#fd022c] top-[8px]"><p className="leading-[16px]">&bull;</p></div></div>
                <div className="[word-break:break-word] content-stretch flex gap-[10px] items-center leading-[0] relative shrink-0 text-[12px] whitespace-nowrap"><div className="flex flex-col font-['Inter'] font-normal justify-center not-italic relative shrink-0 text-[#5f6368]"><p className="leading-[1.5]">Remote viewing</p></div><div className="-translate-y-1/2 absolute flex flex-col font-['Manrope'] font-bold justify-center left-[-12px] text-[#fd022c] top-[8px]"><p className="leading-[16px]">&bull;</p></div></div>
                <div className="[word-break:break-word] content-stretch flex gap-[10px] items-center leading-[0] relative shrink-0 text-[12px] whitespace-nowrap"><div className="flex flex-col font-['Inter'] font-normal justify-center not-italic relative shrink-0 text-[#5f6368]"><p className="leading-[1.5]">TF card &amp; cloud storage</p></div><div className="-translate-y-1/2 absolute flex flex-col font-['Manrope'] font-bold justify-center left-[-12px] text-[#fd022c] top-[8px]"><p className="leading-[16px]">&bull;</p></div></div>
                <div className="[word-break:break-word] content-stretch flex gap-[10px] items-center leading-[0] relative shrink-0 text-[12px] whitespace-nowrap"><div className="flex flex-col font-['Inter'] font-normal justify-center not-italic relative shrink-0 text-[#5f6368]"><p className="leading-[1.5]">Solar charging option on HOUM-170S</p></div><div className="-translate-y-1/2 absolute flex flex-col font-['Manrope'] font-bold justify-center left-[-12px] text-[#fd022c] top-[8px]"><p className="leading-[16px]">&bull;</p></div></div>
            </div>
            <div className="content-start flex flex-wrap gap-y-[8px] items-start relative shrink-0 w-full">
              <div className="content-stretch flex flex-col gap-[8px] items-start justify-center relative shrink-0">
                <div className="[word-break:break-word] flex flex-col font-['Inter'] font-normal justify-center leading-[0] not-italic relative shrink-0 text-[#111] text-[12px] whitespace-nowrap"><p className="leading-[1.5]">Use cases:</p></div>
                <div className="content-stretch flex gap-[8px] items-start relative shrink-0"><div className="[word-break:break-word] flex flex-col font-['Inter'] font-normal justify-center leading-[0] not-italic relative shrink-0 text-[#5f6368] text-[12px] whitespace-nowrap"><p className="leading-[1.5]">Remote Areas</p></div><div className="[word-break:break-word] flex flex-col font-['Inter'] font-medium justify-center leading-[0] not-italic relative shrink-0 text-[#5f6368] text-[14px] whitespace-nowrap"><p className="leading-[1.2]">&middot;</p></div><div className="[word-break:break-word] flex flex-col font-['Inter'] font-normal justify-center leading-[0] not-italic relative shrink-0 text-[#5f6368] text-[12px] whitespace-nowrap"><p className="leading-[1.5]">Temporary Locations</p></div><div className="[word-break:break-word] flex flex-col font-['Inter'] font-medium justify-center leading-[0] not-italic relative shrink-0 text-[#5f6368] text-[14px] whitespace-nowrap"><p className="leading-[1.2]">&middot;</p></div><div className="[word-break:break-word] flex flex-col font-['Inter'] font-normal justify-center leading-[0] not-italic relative shrink-0 text-[#5f6368] text-[12px] whitespace-nowrap"><p className="leading-[1.5]">Outdoor Storage</p></div><div className="[word-break:break-word] flex flex-col font-['Inter'] font-medium justify-center leading-[0] not-italic relative shrink-0 text-[#5f6368] text-[14px] whitespace-nowrap"><p className="leading-[1.2]">&middot;</p></div><div className="[word-break:break-word] flex flex-col font-['Inter'] font-normal justify-center leading-[0] not-italic relative shrink-0 text-[#5f6368] text-[12px] whitespace-nowrap"><p className="leading-[1.5]">Expansion Sites</p></div></div>
              </div>
            </div>
          </div>
        </div>
        <div className="content-center flex flex-wrap gap-[24px] items-center relative shrink-0 w-full">
          <div className="bg-white border border-[#e5e5e5] border-solid content-stretch flex flex-[1_0_0] flex-col gap-[16px] items-start justify-center min-w-[416px] p-[40px] relative rounded-[24px]">
            <div className="content-stretch flex flex-col gap-[8px] items-start relative shrink-0 w-full">
              <div className="[word-break:break-word] flex flex-col font-['Inter'] font-bold justify-center leading-[0] not-italic relative shrink-0 text-[#fd022c] text-[14px] tracking-[1.4px] uppercase w-full"><p className="leading-[20px]">06 &mdash; REMOTE 4G SURVEILLANCE</p></div>
              <div className="[word-break:break-word] flex flex-col font-['Poppins'] justify-center leading-[0] not-italic relative shrink-0 text-[#111] text-[24px] w-full"><h3 className="leading-[1.2]">Stay Connected Beyond the Network</h3></div>
            </div>
            <div className="[word-break:break-word] content-stretch flex flex-col font-['Inter'] font-normal gap-[8px] items-start leading-[0] not-italic pt-[8px] relative shrink-0 w-full">
              <div className="[word-break:break-word] flex flex-col justify-center relative shrink-0 text-[#5f6368] text-[16px] w-full"><p className="leading-[1.5]">Monitor remote retail locations with 4G-enabled cameras and convenient remote viewing.</p></div>
              <div className="content-stretch flex flex-col gap-[4px] items-start relative shrink-0 w-full">
                <div className="flex flex-col justify-center relative shrink-0 text-[#111] text-[16px] w-full"><p className="leading-[1.5]">HOUM-P168 / HOUM-170 / HOUM-170S</p></div>
                <div className="flex flex-col justify-center relative shrink-0 text-[#3f4347] text-[14px] w-full"><p className="font-['Inter'] italic leading-[20px] text-[14px]">4G Outdoor Cameras</p></div>
              </div>
            </div>
            <div className="content-stretch flex flex-col gap-[4px] items-start pl-[16px] relative shrink-0 w-full">
                <div className="[word-break:break-word] content-stretch flex gap-[10px] items-center leading-[0] relative shrink-0 text-[12px] whitespace-nowrap"><div className="flex flex-col font-['Inter'] font-normal justify-center not-italic relative shrink-0 text-[#5f6368]"><p className="leading-[1.5]">4G connectivity</p></div><div className="-translate-y-1/2 absolute flex flex-col font-['Manrope'] font-bold justify-center left-[-12px] text-[#fd022c] top-[8px]"><p className="leading-[16px]">&bull;</p></div></div>
                <div className="[word-break:break-word] content-stretch flex gap-[10px] items-center leading-[0] relative shrink-0 text-[12px] whitespace-nowrap"><div className="flex flex-col font-['Inter'] font-normal justify-center not-italic relative shrink-0 text-[#5f6368]"><p className="leading-[1.5]">Remote viewing</p></div><div className="-translate-y-1/2 absolute flex flex-col font-['Manrope'] font-bold justify-center left-[-12px] text-[#fd022c] top-[8px]"><p className="leading-[16px]">&bull;</p></div></div>
                <div className="[word-break:break-word] content-stretch flex gap-[10px] items-center leading-[0] relative shrink-0 text-[12px] whitespace-nowrap"><div className="flex flex-col font-['Inter'] font-normal justify-center not-italic relative shrink-0 text-[#5f6368]"><p className="leading-[1.5]">Motion detection</p></div><div className="-translate-y-1/2 absolute flex flex-col font-['Manrope'] font-bold justify-center left-[-12px] text-[#fd022c] top-[8px]"><p className="leading-[16px]">&bull;</p></div></div>
                <div className="[word-break:break-word] content-stretch flex gap-[10px] items-center leading-[0] relative shrink-0 text-[12px] whitespace-nowrap"><div className="flex flex-col font-['Inter'] font-normal justify-center not-italic relative shrink-0 text-[#5f6368]"><p className="leading-[1.5]">Day/night IR vision</p></div><div className="-translate-y-1/2 absolute flex flex-col font-['Manrope'] font-bold justify-center left-[-12px] text-[#fd022c] top-[8px]"><p className="leading-[16px]">&bull;</p></div></div>
                <div className="[word-break:break-word] content-stretch flex gap-[10px] items-center leading-[0] relative shrink-0 text-[12px] whitespace-nowrap"><div className="flex flex-col font-['Inter'] font-normal justify-center not-italic relative shrink-0 text-[#5f6368]"><p className="leading-[1.5]">Two-way audio</p></div><div className="-translate-y-1/2 absolute flex flex-col font-['Manrope'] font-bold justify-center left-[-12px] text-[#fd022c] top-[8px]"><p className="leading-[16px]">&bull;</p></div></div>
                <div className="[word-break:break-word] content-stretch flex gap-[10px] items-center leading-[0] relative shrink-0 text-[12px] whitespace-nowrap"><div className="flex flex-col font-['Inter'] font-normal justify-center not-italic relative shrink-0 text-[#5f6368]"><p className="leading-[1.5]">Local &amp; cloud storage</p></div><div className="-translate-y-1/2 absolute flex flex-col font-['Manrope'] font-bold justify-center left-[-12px] text-[#fd022c] top-[8px]"><p className="leading-[16px]">&bull;</p></div></div>
            </div>
            <div className="content-start flex flex-wrap gap-y-[8px] items-start relative shrink-0 w-full">
              <div className="content-stretch flex flex-col gap-[8px] items-start justify-center relative shrink-0">
                <div className="[word-break:break-word] flex flex-col font-['Inter'] font-normal justify-center leading-[0] not-italic relative shrink-0 text-[#111] text-[12px] whitespace-nowrap"><p className="leading-[1.5]">Use cases:</p></div>
                <div className="content-stretch flex gap-[8px] items-start relative shrink-0"><div className="[word-break:break-word] flex flex-col font-['Inter'] font-normal justify-center leading-[0] not-italic relative shrink-0 text-[#5f6368] text-[12px] whitespace-nowrap"><p className="leading-[1.5]">Remote Stores</p></div><div className="[word-break:break-word] flex flex-col font-['Inter'] font-medium justify-center leading-[0] not-italic relative shrink-0 text-[#5f6368] text-[14px] whitespace-nowrap"><p className="leading-[1.2]">&middot;</p></div><div className="[word-break:break-word] flex flex-col font-['Inter'] font-normal justify-center leading-[0] not-italic relative shrink-0 text-[#5f6368] text-[12px] whitespace-nowrap"><p className="leading-[1.5]">Temporary Sites</p></div><div className="[word-break:break-word] flex flex-col font-['Inter'] font-medium justify-center leading-[0] not-italic relative shrink-0 text-[#5f6368] text-[14px] whitespace-nowrap"><p className="leading-[1.2]">&middot;</p></div><div className="[word-break:break-word] flex flex-col font-['Inter'] font-normal justify-center leading-[0] not-italic relative shrink-0 text-[#5f6368] text-[12px] whitespace-nowrap"><p className="leading-[1.5]">Isolated Locations</p></div><div className="[word-break:break-word] flex flex-col font-['Inter'] font-medium justify-center leading-[0] not-italic relative shrink-0 text-[#5f6368] text-[14px] whitespace-nowrap"><p className="leading-[1.2]">&middot;</p></div><div className="[word-break:break-word] flex flex-col font-['Inter'] font-normal justify-center leading-[0] not-italic relative shrink-0 text-[#5f6368] text-[12px] whitespace-nowrap"><p className="leading-[1.5]">New Locations</p></div></div>
              </div>
            </div>
          </div>
          <div className="bg-[#3f4347] flex-[1_0_0] h-[448px] min-w-[416px] overflow-clip relative rounded-[24px] shadow-[0px_25px_50px_-12px_rgba(0,0,0,0.25)]"><div className="absolute inset-0 overflow-hidden pointer-events-none"><img alt="Outdoor storage yard" className="absolute inset-0 max-w-none object-cover size-full" src={imgcf14b3085176} /></div></div>
        </div>
      </div>
      </div>
    </>
  );
}
