import { Link } from 'react-router-dom';
import img8c3d7b264e9a from '@/assets/8c3d7b264e9a.svg';
import img0a245a08615e from '@/assets/0a245a08615e.webp';
import imgd58418bbc3a0 from '@/assets/d58418bbc3a0.svg';

export default function VideosSection() {
  return (
    <>
      <div className="flex flex-col gap-[32px] items-start relative size-full">
        <div className="content-start flex flex-wrap gap-[0px_16px] items-center w-full">
          <Link to="/support-technical-videos" aria-label="Back to Technical Videos" className="relative shrink-0 size-[32px] hover:opacity-70"><img alt="" className="absolute block inset-0 max-w-none size-full" src={img8c3d7b264e9a} /></Link>
          <h2 className="font-['Poppins'] leading-[1.2] text-[#111] text-[24px] whitespace-nowrap">Blank</h2>
        </div>
        <div className="content-start flex flex-wrap gap-[24px] items-start w-full"><div className="group bg-white border border-[rgba(227,190,186,0.3)] border-solid drop-shadow-[0px_4px_10px_rgba(0,0,0,0.05)] flex flex-col items-start p-px relative rounded-[24px] shrink-0 w-[416px] cursor-pointer hover:border-[#fd022c] transition-colors">
        <div className="h-[304px] relative rounded-[24px] shrink-0 w-full"><img alt="How to add IP cameras in the \u2013 video thumbnail" className="absolute inset-0 max-w-none object-cover pointer-events-none rounded-[24px] size-full" src={img0a245a08615e} /></div>
        <div className="flex flex-col items-start p-[24px] w-full"><h3 className="font-['Inter'] font-medium leading-[1.2] text-[#111] text-[18px] w-full group-hover:text-[#fd022c]">How to add IP cameras in the</h3></div>
        <div className="absolute left-[171px] size-[72px] top-[116px] transition-transform group-hover:scale-110"><img alt="" className="absolute block inset-0 max-w-none size-full" src={imgd58418bbc3a0} /></div>
        <div className="absolute bg-[rgba(17,17,17,0.8)] flex items-center justify-center left-[348px] px-[4px] py-[2px] rounded-[4px] top-[269px]"><p className="font-['Inter'] font-medium leading-[1.2] text-[16px] text-white whitespace-nowrap">02:18</p></div>
      </div><div className="group bg-white border border-[rgba(227,190,186,0.3)] border-solid drop-shadow-[0px_4px_10px_rgba(0,0,0,0.05)] flex flex-col items-start p-px relative rounded-[24px] shrink-0 w-[416px] cursor-pointer hover:border-[#fd022c] transition-colors">
        <div className="h-[304px] relative rounded-[24px] shrink-0 w-full"><img alt="How to online through DDNS? \u2013 video thumbnail" className="absolute inset-0 max-w-none object-cover pointer-events-none rounded-[24px] size-full" src={img0a245a08615e} /></div>
        <div className="flex flex-col items-start p-[24px] w-full"><h3 className="font-['Inter'] font-medium leading-[1.2] text-[#111] text-[18px] w-full group-hover:text-[#fd022c]">How to online through DDNS?</h3></div>
        <div className="absolute left-[171px] size-[72px] top-[116px] transition-transform group-hover:scale-110"><img alt="" className="absolute block inset-0 max-w-none size-full" src={imgd58418bbc3a0} /></div>
        <div className="absolute bg-[rgba(17,17,17,0.8)] flex items-center justify-center left-[348px] px-[4px] py-[2px] rounded-[4px] top-[269px]"><p className="font-['Inter'] font-medium leading-[1.2] text-[16px] text-white whitespace-nowrap">02:18</p></div>
      </div><div className="group bg-white border border-[rgba(227,190,186,0.3)] border-solid drop-shadow-[0px_4px_10px_rgba(0,0,0,0.05)] flex flex-col items-start p-px relative rounded-[24px] shrink-0 w-[416px] cursor-pointer hover:border-[#fd022c] transition-colors">
        <div className="h-[304px] relative rounded-[24px] shrink-0 w-full"><img alt="Enabling email configuration \u2013 video thumbnail" className="absolute inset-0 max-w-none object-cover pointer-events-none rounded-[24px] size-full" src={img0a245a08615e} /></div>
        <div className="flex flex-col items-start p-[24px] w-full"><h3 className="font-['Inter'] font-medium leading-[1.2] text-[#111] text-[18px] w-full group-hover:text-[#fd022c]">Enabling email configuration</h3></div>
        <div className="absolute left-[171px] size-[72px] top-[116px] transition-transform group-hover:scale-110"><img alt="" className="absolute block inset-0 max-w-none size-full" src={imgd58418bbc3a0} /></div>
        <div className="absolute bg-[rgba(17,17,17,0.8)] flex items-center justify-center left-[348px] px-[4px] py-[2px] rounded-[4px] top-[269px]"><p className="font-['Inter'] font-medium leading-[1.2] text-[16px] text-white whitespace-nowrap">02:18</p></div>
      </div><div className="group bg-white border border-[rgba(227,190,186,0.3)] border-solid drop-shadow-[0px_4px_10px_rgba(0,0,0,0.05)] flex flex-col items-start p-px relative rounded-[24px] shrink-0 w-[416px] cursor-pointer hover:border-[#fd022c] transition-colors">
        <div className="h-[304px] relative rounded-[24px] shrink-0 w-full"><img alt="Enabling email configuration \u2013 video thumbnail" className="absolute inset-0 max-w-none object-cover pointer-events-none rounded-[24px] size-full" src={img0a245a08615e} /></div>
        <div className="flex flex-col items-start p-[24px] w-full"><h3 className="font-['Inter'] font-medium leading-[1.2] text-[#111] text-[18px] w-full group-hover:text-[#fd022c]">Enabling email configuration</h3></div>
        <div className="absolute left-[171px] size-[72px] top-[116px] transition-transform group-hover:scale-110"><img alt="" className="absolute block inset-0 max-w-none size-full" src={imgd58418bbc3a0} /></div>
        <div className="absolute bg-[rgba(17,17,17,0.8)] flex items-center justify-center left-[348px] px-[4px] py-[2px] rounded-[4px] top-[269px]"><p className="font-['Inter'] font-medium leading-[1.2] text-[16px] text-white whitespace-nowrap">02:18</p></div>
      </div><div className="group bg-white border border-[rgba(227,190,186,0.3)] border-solid drop-shadow-[0px_4px_10px_rgba(0,0,0,0.05)] flex flex-col items-start p-px relative rounded-[24px] shrink-0 w-[416px] cursor-pointer hover:border-[#fd022c] transition-colors">
        <div className="h-[304px] relative rounded-[24px] shrink-0 w-full"><img alt="Enabling email configuration \u2013 video thumbnail" className="absolute inset-0 max-w-none object-cover pointer-events-none rounded-[24px] size-full" src={img0a245a08615e} /></div>
        <div className="flex flex-col items-start p-[24px] w-full"><h3 className="font-['Inter'] font-medium leading-[1.2] text-[#111] text-[18px] w-full group-hover:text-[#fd022c]">Enabling email configuration</h3></div>
        <div className="absolute left-[171px] size-[72px] top-[116px] transition-transform group-hover:scale-110"><img alt="" className="absolute block inset-0 max-w-none size-full" src={imgd58418bbc3a0} /></div>
        <div className="absolute bg-[rgba(17,17,17,0.8)] flex items-center justify-center left-[348px] px-[4px] py-[2px] rounded-[4px] top-[269px]"><p className="font-['Inter'] font-medium leading-[1.2] text-[16px] text-white whitespace-nowrap">02:18</p></div>
      </div><div className="group bg-white border border-[rgba(227,190,186,0.3)] border-solid drop-shadow-[0px_4px_10px_rgba(0,0,0,0.05)] flex flex-col items-start p-px relative rounded-[24px] shrink-0 w-[416px] cursor-pointer hover:border-[#fd022c] transition-colors">
        <div className="h-[304px] relative rounded-[24px] shrink-0 w-full"><img alt="Enabling email configuration \u2013 video thumbnail" className="absolute inset-0 max-w-none object-cover pointer-events-none rounded-[24px] size-full" src={img0a245a08615e} /></div>
        <div className="flex flex-col items-start p-[24px] w-full"><h3 className="font-['Inter'] font-medium leading-[1.2] text-[#111] text-[18px] w-full group-hover:text-[#fd022c]">Enabling email configuration</h3></div>
        <div className="absolute left-[171px] size-[72px] top-[116px] transition-transform group-hover:scale-110"><img alt="" className="absolute block inset-0 max-w-none size-full" src={imgd58418bbc3a0} /></div>
        <div className="absolute bg-[rgba(17,17,17,0.8)] flex items-center justify-center left-[348px] px-[4px] py-[2px] rounded-[4px] top-[269px]"><p className="font-['Inter'] font-medium leading-[1.2] text-[16px] text-white whitespace-nowrap">02:18</p></div>
      </div><div className="group bg-white border border-[rgba(227,190,186,0.3)] border-solid drop-shadow-[0px_4px_10px_rgba(0,0,0,0.05)] flex flex-col items-start p-px relative rounded-[24px] shrink-0 w-[416px] cursor-pointer hover:border-[#fd022c] transition-colors">
        <div className="h-[304px] relative rounded-[24px] shrink-0 w-full"><img alt="Enabling email configuration \u2013 video thumbnail" className="absolute inset-0 max-w-none object-cover pointer-events-none rounded-[24px] size-full" src={img0a245a08615e} /></div>
        <div className="flex flex-col items-start p-[24px] w-full"><h3 className="font-['Inter'] font-medium leading-[1.2] text-[#111] text-[18px] w-full group-hover:text-[#fd022c]">Enabling email configuration</h3></div>
        <div className="absolute left-[171px] size-[72px] top-[116px] transition-transform group-hover:scale-110"><img alt="" className="absolute block inset-0 max-w-none size-full" src={imgd58418bbc3a0} /></div>
        <div className="absolute bg-[rgba(17,17,17,0.8)] flex items-center justify-center left-[348px] px-[4px] py-[2px] rounded-[4px] top-[269px]"><p className="font-['Inter'] font-medium leading-[1.2] text-[16px] text-white whitespace-nowrap">02:18</p></div>
      </div><div className="group bg-white border border-[rgba(227,190,186,0.3)] border-solid drop-shadow-[0px_4px_10px_rgba(0,0,0,0.05)] flex flex-col items-start p-px relative rounded-[24px] shrink-0 w-[416px] cursor-pointer hover:border-[#fd022c] transition-colors">
        <div className="h-[304px] relative rounded-[24px] shrink-0 w-full"><img alt="Enabling email configuration \u2013 video thumbnail" className="absolute inset-0 max-w-none object-cover pointer-events-none rounded-[24px] size-full" src={img0a245a08615e} /></div>
        <div className="flex flex-col items-start p-[24px] w-full"><h3 className="font-['Inter'] font-medium leading-[1.2] text-[#111] text-[18px] w-full group-hover:text-[#fd022c]">Enabling email configuration</h3></div>
        <div className="absolute left-[171px] size-[72px] top-[116px] transition-transform group-hover:scale-110"><img alt="" className="absolute block inset-0 max-w-none size-full" src={imgd58418bbc3a0} /></div>
        <div className="absolute bg-[rgba(17,17,17,0.8)] flex items-center justify-center left-[348px] px-[4px] py-[2px] rounded-[4px] top-[269px]"><p className="font-['Inter'] font-medium leading-[1.2] text-[16px] text-white whitespace-nowrap">02:18</p></div>
      </div><div className="group bg-white border border-[rgba(227,190,186,0.3)] border-solid drop-shadow-[0px_4px_10px_rgba(0,0,0,0.05)] flex flex-col items-start p-px relative rounded-[24px] shrink-0 w-[416px] cursor-pointer hover:border-[#fd022c] transition-colors">
        <div className="h-[304px] relative rounded-[24px] shrink-0 w-full"><img alt="Enabling email configuration \u2013 video thumbnail" className="absolute inset-0 max-w-none object-cover pointer-events-none rounded-[24px] size-full" src={img0a245a08615e} /></div>
        <div className="flex flex-col items-start p-[24px] w-full"><h3 className="font-['Inter'] font-medium leading-[1.2] text-[#111] text-[18px] w-full group-hover:text-[#fd022c]">Enabling email configuration</h3></div>
        <div className="absolute left-[171px] size-[72px] top-[116px] transition-transform group-hover:scale-110"><img alt="" className="absolute block inset-0 max-w-none size-full" src={imgd58418bbc3a0} /></div>
        <div className="absolute bg-[rgba(17,17,17,0.8)] flex items-center justify-center left-[348px] px-[4px] py-[2px] rounded-[4px] top-[269px]"><p className="font-['Inter'] font-medium leading-[1.2] text-[16px] text-white whitespace-nowrap">02:18</p></div>
      </div><div className="group bg-white border border-[rgba(227,190,186,0.3)] border-solid drop-shadow-[0px_4px_10px_rgba(0,0,0,0.05)] flex flex-col items-start p-px relative rounded-[24px] shrink-0 w-[416px] cursor-pointer hover:border-[#fd022c] transition-colors">
        <div className="h-[304px] relative rounded-[24px] shrink-0 w-full"><img alt="Enabling email configuration \u2013 video thumbnail" className="absolute inset-0 max-w-none object-cover pointer-events-none rounded-[24px] size-full" src={img0a245a08615e} /></div>
        <div className="flex flex-col items-start p-[24px] w-full"><h3 className="font-['Inter'] font-medium leading-[1.2] text-[#111] text-[18px] w-full group-hover:text-[#fd022c]">Enabling email configuration</h3></div>
        <div className="absolute left-[171px] size-[72px] top-[116px] transition-transform group-hover:scale-110"><img alt="" className="absolute block inset-0 max-w-none size-full" src={imgd58418bbc3a0} /></div>
        <div className="absolute bg-[rgba(17,17,17,0.8)] flex items-center justify-center left-[348px] px-[4px] py-[2px] rounded-[4px] top-[269px]"><p className="font-['Inter'] font-medium leading-[1.2] text-[16px] text-white whitespace-nowrap">02:18</p></div>
      </div><div className="group bg-white border border-[rgba(227,190,186,0.3)] border-solid drop-shadow-[0px_4px_10px_rgba(0,0,0,0.05)] flex flex-col items-start p-px relative rounded-[24px] shrink-0 w-[416px] cursor-pointer hover:border-[#fd022c] transition-colors">
        <div className="h-[304px] relative rounded-[24px] shrink-0 w-full"><img alt="Enabling email configuration \u2013 video thumbnail" className="absolute inset-0 max-w-none object-cover pointer-events-none rounded-[24px] size-full" src={img0a245a08615e} /></div>
        <div className="flex flex-col items-start p-[24px] w-full"><h3 className="font-['Inter'] font-medium leading-[1.2] text-[#111] text-[18px] w-full group-hover:text-[#fd022c]">Enabling email configuration</h3></div>
        <div className="absolute left-[171px] size-[72px] top-[116px] transition-transform group-hover:scale-110"><img alt="" className="absolute block inset-0 max-w-none size-full" src={imgd58418bbc3a0} /></div>
        <div className="absolute bg-[rgba(17,17,17,0.8)] flex items-center justify-center left-[348px] px-[4px] py-[2px] rounded-[4px] top-[269px]"><p className="font-['Inter'] font-medium leading-[1.2] text-[16px] text-white whitespace-nowrap">02:18</p></div>
      </div><div className="group bg-white border border-[rgba(227,190,186,0.3)] border-solid drop-shadow-[0px_4px_10px_rgba(0,0,0,0.05)] flex flex-col items-start p-px relative rounded-[24px] shrink-0 w-[416px] cursor-pointer hover:border-[#fd022c] transition-colors">
        <div className="h-[304px] relative rounded-[24px] shrink-0 w-full"><img alt="Enabling email configuration \u2013 video thumbnail" className="absolute inset-0 max-w-none object-cover pointer-events-none rounded-[24px] size-full" src={img0a245a08615e} /></div>
        <div className="flex flex-col items-start p-[24px] w-full"><h3 className="font-['Inter'] font-medium leading-[1.2] text-[#111] text-[18px] w-full group-hover:text-[#fd022c]">Enabling email configuration</h3></div>
        <div className="absolute left-[171px] size-[72px] top-[116px] transition-transform group-hover:scale-110"><img alt="" className="absolute block inset-0 max-w-none size-full" src={imgd58418bbc3a0} /></div>
        <div className="absolute bg-[rgba(17,17,17,0.8)] flex items-center justify-center left-[348px] px-[4px] py-[2px] rounded-[4px] top-[269px]"><p className="font-['Inter'] font-medium leading-[1.2] text-[16px] text-white whitespace-nowrap">02:18</p></div>
      </div></div>
      </div>
    </>
  );
}
