import { Link } from 'react-router-dom';
import img0a245a08615e from '@/assets/0a245a08615e.webp';
import imgd58418bbc3a0 from '@/assets/d58418bbc3a0.svg';

export default function VideosSection() {
  return (
    <>
      <div className="flex flex-col gap-[40px] items-start relative size-full">
      <section className="flex flex-col gap-[32px] items-start w-full">
        <div className="flex items-center justify-between w-full"><h2 className="font-['Poppins'] leading-[1.2] text-[#111] text-[24px] whitespace-nowrap">Orange Video Recoder</h2><Link to="/support-technical-videos-2" className="font-['Inter'] font-medium leading-[24px] text-[#111] text-[16px] whitespace-nowrap hover:text-[#fd022c]">See All</Link></div>
        <div className="flex gap-[24px] items-start w-full"><Link to="/support-technical-videos-2" className="group bg-white border border-[rgba(227,190,186,0.3)] border-solid drop-shadow-[0px_4px_10px_rgba(0,0,0,0.05)] flex flex-col items-start p-px relative rounded-[24px] shrink-0 w-[416px] cursor-pointer hover:border-[#fd022c] transition-colors">
        <div className="h-[304px] relative rounded-[24px] shrink-0 w-full"><img alt="How to add IP cameras in the \u2013 video thumbnail" className="absolute inset-0 max-w-none object-cover pointer-events-none rounded-[24px] size-full" src={img0a245a08615e} /></div>
        <div className="flex flex-col items-start p-[24px] w-full"><h3 className="font-['Inter'] font-medium leading-[1.2] text-[#111] text-[18px] w-full group-hover:text-[#fd022c]">How to add IP cameras in the</h3></div>
        <div className="absolute left-[171px] size-[72px] top-[116px] transition-transform group-hover:scale-110"><img alt="" className="absolute block inset-0 max-w-none size-full" src={imgd58418bbc3a0} /></div>
        <div className="absolute bg-[rgba(17,17,17,0.8)] flex items-center justify-center left-[348px] px-[4px] py-[2px] rounded-[4px] top-[269px]"><p className="font-['Inter'] font-medium leading-[1.2] text-[16px] text-white whitespace-nowrap">02:18</p></div>
      </Link><Link to="/support-technical-videos-2" className="group bg-white border border-[rgba(227,190,186,0.3)] border-solid drop-shadow-[0px_4px_10px_rgba(0,0,0,0.05)] flex flex-col items-start p-px relative rounded-[24px] shrink-0 w-[416px] cursor-pointer hover:border-[#fd022c] transition-colors">
        <div className="h-[304px] relative rounded-[24px] shrink-0 w-full"><img alt="How to online through DDNS? \u2013 video thumbnail" className="absolute inset-0 max-w-none object-cover pointer-events-none rounded-[24px] size-full" src={img0a245a08615e} /></div>
        <div className="flex flex-col items-start p-[24px] w-full"><h3 className="font-['Inter'] font-medium leading-[1.2] text-[#111] text-[18px] w-full group-hover:text-[#fd022c]">How to online through DDNS?</h3></div>
        <div className="absolute left-[171px] size-[72px] top-[116px] transition-transform group-hover:scale-110"><img alt="" className="absolute block inset-0 max-w-none size-full" src={imgd58418bbc3a0} /></div>
        <div className="absolute bg-[rgba(17,17,17,0.8)] flex items-center justify-center left-[348px] px-[4px] py-[2px] rounded-[4px] top-[269px]"><p className="font-['Inter'] font-medium leading-[1.2] text-[16px] text-white whitespace-nowrap">02:18</p></div>
      </Link><Link to="/support-technical-videos-2" className="group bg-white border border-[rgba(227,190,186,0.3)] border-solid drop-shadow-[0px_4px_10px_rgba(0,0,0,0.05)] flex flex-col items-start p-px relative rounded-[24px] shrink-0 w-[416px] cursor-pointer hover:border-[#fd022c] transition-colors">
        <div className="h-[304px] relative rounded-[24px] shrink-0 w-full"><img alt="Enabling email configuration \u2013 video thumbnail" className="absolute inset-0 max-w-none object-cover pointer-events-none rounded-[24px] size-full" src={img0a245a08615e} /></div>
        <div className="flex flex-col items-start p-[24px] w-full"><h3 className="font-['Inter'] font-medium leading-[1.2] text-[#111] text-[18px] w-full group-hover:text-[#fd022c]">Enabling email configuration</h3></div>
        <div className="absolute left-[171px] size-[72px] top-[116px] transition-transform group-hover:scale-110"><img alt="" className="absolute block inset-0 max-w-none size-full" src={imgd58418bbc3a0} /></div>
        <div className="absolute bg-[rgba(17,17,17,0.8)] flex items-center justify-center left-[348px] px-[4px] py-[2px] rounded-[4px] top-[269px]"><p className="font-['Inter'] font-medium leading-[1.2] text-[16px] text-white whitespace-nowrap">02:18</p></div>
      </Link></div>
      </section>
      <section className="flex flex-col gap-[32px] items-start w-full">
        <div className="flex items-center justify-between w-full"><h2 className="font-['Poppins'] leading-[1.2] text-[#111] text-[24px] whitespace-nowrap">Red Video Recoder</h2><Link to="/support-technical-videos-2" className="font-['Inter'] font-medium leading-[24px] text-[#111] text-[16px] whitespace-nowrap hover:text-[#fd022c]">See All</Link></div>
        <div className="flex gap-[24px] items-start w-full"><Link to="/support-technical-videos-2" className="group bg-white border border-[rgba(227,190,186,0.3)] border-solid drop-shadow-[0px_4px_10px_rgba(0,0,0,0.05)] flex flex-col items-start p-px relative rounded-[24px] shrink-0 w-[416px] cursor-pointer hover:border-[#fd022c] transition-colors">
        <div className="h-[304px] relative rounded-[24px] shrink-0 w-full"><img alt="How to format HDD \u2013 video thumbnail" className="absolute inset-0 max-w-none object-cover pointer-events-none rounded-[24px] size-full" src={img0a245a08615e} /></div>
        <div className="flex flex-col items-start p-[24px] w-full"><h3 className="font-['Inter'] font-medium leading-[1.2] text-[#111] text-[18px] w-full group-hover:text-[#fd022c]">How to format HDD</h3></div>
        <div className="absolute left-[171px] size-[72px] top-[116px] transition-transform group-hover:scale-110"><img alt="" className="absolute block inset-0 max-w-none size-full" src={imgd58418bbc3a0} /></div>
        <div className="absolute bg-[rgba(17,17,17,0.8)] flex items-center justify-center left-[348px] px-[4px] py-[2px] rounded-[4px] top-[269px]"><p className="font-['Inter'] font-medium leading-[1.2] text-[16px] text-white whitespace-nowrap">02:18</p></div>
      </Link><Link to="/support-technical-videos-2" className="group bg-white border border-[rgba(227,190,186,0.3)] border-solid drop-shadow-[0px_4px_10px_rgba(0,0,0,0.05)] flex flex-col items-start p-px relative rounded-[24px] shrink-0 w-[416px] cursor-pointer hover:border-[#fd022c] transition-colors">
        <div className="h-[304px] relative rounded-[24px] shrink-0 w-full"><img alt="How to reboot the DVR \u2013 video thumbnail" className="absolute inset-0 max-w-none object-cover pointer-events-none rounded-[24px] size-full" src={img0a245a08615e} /></div>
        <div className="flex flex-col items-start p-[24px] w-full"><h3 className="font-['Inter'] font-medium leading-[1.2] text-[#111] text-[18px] w-full group-hover:text-[#fd022c]">How to reboot the DVR</h3></div>
        <div className="absolute left-[171px] size-[72px] top-[116px] transition-transform group-hover:scale-110"><img alt="" className="absolute block inset-0 max-w-none size-full" src={imgd58418bbc3a0} /></div>
        <div className="absolute bg-[rgba(17,17,17,0.8)] flex items-center justify-center left-[348px] px-[4px] py-[2px] rounded-[4px] top-[269px]"><p className="font-['Inter'] font-medium leading-[1.2] text-[16px] text-white whitespace-nowrap">02:18</p></div>
      </Link><Link to="/support-technical-videos-2" className="group bg-white border border-[rgba(227,190,186,0.3)] border-solid drop-shadow-[0px_4px_10px_rgba(0,0,0,0.05)] flex flex-col items-start p-px relative rounded-[24px] shrink-0 w-[416px] cursor-pointer hover:border-[#fd022c] transition-colors">
        <div className="h-[304px] relative rounded-[24px] shrink-0 w-full"><img alt="How to modify date and time \u2013 video thumbnail" className="absolute inset-0 max-w-none object-cover pointer-events-none rounded-[24px] size-full" src={img0a245a08615e} /></div>
        <div className="flex flex-col items-start p-[24px] w-full"><h3 className="font-['Inter'] font-medium leading-[1.2] text-[#111] text-[18px] w-full group-hover:text-[#fd022c]">How to modify date and time</h3></div>
        <div className="absolute left-[171px] size-[72px] top-[116px] transition-transform group-hover:scale-110"><img alt="" className="absolute block inset-0 max-w-none size-full" src={imgd58418bbc3a0} /></div>
        <div className="absolute bg-[rgba(17,17,17,0.8)] flex items-center justify-center left-[348px] px-[4px] py-[2px] rounded-[4px] top-[269px]"><p className="font-['Inter'] font-medium leading-[1.2] text-[16px] text-white whitespace-nowrap">02:18</p></div>
      </Link></div>
      </section>
      <section className="flex flex-col gap-[32px] items-start w-full">
        <div className="flex items-center justify-between w-full"><h2 className="font-['Poppins'] leading-[1.2] text-[#111] text-[24px] whitespace-nowrap">How to modify date and time</h2><Link to="/support-technical-videos-2" className="font-['Inter'] font-medium leading-[24px] text-[#111] text-[16px] whitespace-nowrap hover:text-[#fd022c]">See All</Link></div>
        <div className="flex gap-[24px] items-start w-full"><Link to="/support-technical-videos-2" className="group bg-white border border-[rgba(227,190,186,0.3)] border-solid drop-shadow-[0px_4px_10px_rgba(0,0,0,0.05)] flex flex-col items-start p-px relative rounded-[24px] shrink-0 w-[416px] cursor-pointer hover:border-[#fd022c] transition-colors">
        <div className="h-[304px] relative rounded-[24px] shrink-0 w-full"><img alt="How to do encode settings in \u2013 video thumbnail" className="absolute inset-0 max-w-none object-cover pointer-events-none rounded-[24px] size-full" src={img0a245a08615e} /></div>
        <div className="flex flex-col items-start p-[24px] w-full"><h3 className="font-['Inter'] font-medium leading-[1.2] text-[#111] text-[18px] w-full group-hover:text-[#fd022c]">How to do encode settings in</h3></div>
        <div className="absolute left-[171px] size-[72px] top-[116px] transition-transform group-hover:scale-110"><img alt="" className="absolute block inset-0 max-w-none size-full" src={imgd58418bbc3a0} /></div>
        <div className="absolute bg-[rgba(17,17,17,0.8)] flex items-center justify-center left-[348px] px-[4px] py-[2px] rounded-[4px] top-[269px]"><p className="font-['Inter'] font-medium leading-[1.2] text-[16px] text-white whitespace-nowrap">02:18</p></div>
      </Link><Link to="/support-technical-videos-2" className="group bg-white border border-[rgba(227,190,186,0.3)] border-solid drop-shadow-[0px_4px_10px_rgba(0,0,0,0.05)] flex flex-col items-start p-px relative rounded-[24px] shrink-0 w-[416px] cursor-pointer hover:border-[#fd022c] transition-colors">
        <div className="h-[304px] relative rounded-[24px] shrink-0 w-full"><img alt="How to change IP address of IP \u2013 video thumbnail" className="absolute inset-0 max-w-none object-cover pointer-events-none rounded-[24px] size-full" src={img0a245a08615e} /></div>
        <div className="flex flex-col items-start p-[24px] w-full"><h3 className="font-['Inter'] font-medium leading-[1.2] text-[#111] text-[18px] w-full group-hover:text-[#fd022c]">How to change IP address of IP</h3></div>
        <div className="absolute left-[171px] size-[72px] top-[116px] transition-transform group-hover:scale-110"><img alt="" className="absolute block inset-0 max-w-none size-full" src={imgd58418bbc3a0} /></div>
        <div className="absolute bg-[rgba(17,17,17,0.8)] flex items-center justify-center left-[348px] px-[4px] py-[2px] rounded-[4px] top-[269px]"><p className="font-['Inter'] font-medium leading-[1.2] text-[16px] text-white whitespace-nowrap">02:18</p></div>
      </Link><Link to="/support-technical-videos-2" className="group bg-white border border-[rgba(227,190,186,0.3)] border-solid drop-shadow-[0px_4px_10px_rgba(0,0,0,0.05)] flex flex-col items-start p-px relative rounded-[24px] shrink-0 w-[416px] cursor-pointer hover:border-[#fd022c] transition-colors">
        <div className="h-[304px] relative rounded-[24px] shrink-0 w-full"><img alt="How to change the IP camera \u2013 video thumbnail" className="absolute inset-0 max-w-none object-cover pointer-events-none rounded-[24px] size-full" src={img0a245a08615e} /></div>
        <div className="flex flex-col items-start p-[24px] w-full"><h3 className="font-['Inter'] font-medium leading-[1.2] text-[#111] text-[18px] w-full group-hover:text-[#fd022c]">How to change the IP camera</h3></div>
        <div className="absolute left-[171px] size-[72px] top-[116px] transition-transform group-hover:scale-110"><img alt="" className="absolute block inset-0 max-w-none size-full" src={imgd58418bbc3a0} /></div>
        <div className="absolute bg-[rgba(17,17,17,0.8)] flex items-center justify-center left-[348px] px-[4px] py-[2px] rounded-[4px] top-[269px]"><p className="font-['Inter'] font-medium leading-[1.2] text-[16px] text-white whitespace-nowrap">02:18</p></div>
      </Link></div>
      </section>
      <section className="flex flex-col gap-[32px] items-start w-full">
        <div className="flex items-center justify-between w-full"><h2 className="font-['Poppins'] leading-[1.2] text-[#111] text-[24px] whitespace-nowrap">Indigo IPC</h2><Link to="/support-technical-videos-2" className="font-['Inter'] font-medium leading-[24px] text-[#111] text-[16px] whitespace-nowrap hover:text-[#fd022c]">See All</Link></div>
        <div className="flex gap-[24px] items-start w-full"><Link to="/support-technical-videos-2" className="group bg-white border border-[rgba(227,190,186,0.3)] border-solid drop-shadow-[0px_4px_10px_rgba(0,0,0,0.05)] flex flex-col items-start p-px relative rounded-[24px] shrink-0 w-[416px] cursor-pointer hover:border-[#fd022c] transition-colors">
        <div className="h-[304px] relative rounded-[24px] shrink-0 w-full"><img alt="Change the IP camera name \u2013 video thumbnail" className="absolute inset-0 max-w-none object-cover pointer-events-none rounded-[24px] size-full" src={img0a245a08615e} /></div>
        <div className="flex flex-col items-start p-[24px] w-full"><h3 className="font-['Inter'] font-medium leading-[1.2] text-[#111] text-[18px] w-full group-hover:text-[#fd022c]">Change the IP camera name</h3></div>
        <div className="absolute left-[171px] size-[72px] top-[116px] transition-transform group-hover:scale-110"><img alt="" className="absolute block inset-0 max-w-none size-full" src={imgd58418bbc3a0} /></div>
        <div className="absolute bg-[rgba(17,17,17,0.8)] flex items-center justify-center left-[348px] px-[4px] py-[2px] rounded-[4px] top-[269px]"><p className="font-['Inter'] font-medium leading-[1.2] text-[16px] text-white whitespace-nowrap">02:18</p></div>
      </Link><Link to="/support-technical-videos-2" className="group bg-white border border-[rgba(227,190,186,0.3)] border-solid drop-shadow-[0px_4px_10px_rgba(0,0,0,0.05)] flex flex-col items-start p-px relative rounded-[24px] shrink-0 w-[416px] cursor-pointer hover:border-[#fd022c] transition-colors">
        <div className="h-[304px] relative rounded-[24px] shrink-0 w-full"><img alt="How to do enable DDNS in IPC \u2013 video thumbnail" className="absolute inset-0 max-w-none object-cover pointer-events-none rounded-[24px] size-full" src={img0a245a08615e} /></div>
        <div className="flex flex-col items-start p-[24px] w-full"><h3 className="font-['Inter'] font-medium leading-[1.2] text-[#111] text-[18px] w-full group-hover:text-[#fd022c]">How to do enable DDNS in IPC</h3></div>
        <div className="absolute left-[171px] size-[72px] top-[116px] transition-transform group-hover:scale-110"><img alt="" className="absolute block inset-0 max-w-none size-full" src={imgd58418bbc3a0} /></div>
        <div className="absolute bg-[rgba(17,17,17,0.8)] flex items-center justify-center left-[348px] px-[4px] py-[2px] rounded-[4px] top-[269px]"><p className="font-['Inter'] font-medium leading-[1.2] text-[16px] text-white whitespace-nowrap">02:18</p></div>
      </Link><Link to="/support-technical-videos-2" className="group bg-white border border-[rgba(227,190,186,0.3)] border-solid drop-shadow-[0px_4px_10px_rgba(0,0,0,0.05)] flex flex-col items-start p-px relative rounded-[24px] shrink-0 w-[416px] cursor-pointer hover:border-[#fd022c] transition-colors">
        <div className="h-[304px] relative rounded-[24px] shrink-0 w-full"><img alt="How to enable motion event \u2013 video thumbnail" className="absolute inset-0 max-w-none object-cover pointer-events-none rounded-[24px] size-full" src={img0a245a08615e} /></div>
        <div className="flex flex-col items-start p-[24px] w-full"><h3 className="font-['Inter'] font-medium leading-[1.2] text-[#111] text-[18px] w-full group-hover:text-[#fd022c]">How to enable motion event</h3></div>
        <div className="absolute left-[171px] size-[72px] top-[116px] transition-transform group-hover:scale-110"><img alt="" className="absolute block inset-0 max-w-none size-full" src={imgd58418bbc3a0} /></div>
        <div className="absolute bg-[rgba(17,17,17,0.8)] flex items-center justify-center left-[348px] px-[4px] py-[2px] rounded-[4px] top-[269px]"><p className="font-['Inter'] font-medium leading-[1.2] text-[16px] text-white whitespace-nowrap">02:18</p></div>
      </Link></div>
      </section>
      <section className="flex flex-col gap-[32px] items-start w-full">
        <div className="flex items-center justify-between w-full"><h2 className="font-['Poppins'] leading-[1.2] text-[#111] text-[24px] whitespace-nowrap">Orange IPC</h2><Link to="/support-technical-videos-2" className="font-['Inter'] font-medium leading-[24px] text-[#111] text-[16px] whitespace-nowrap hover:text-[#fd022c]">See All</Link></div>
        <div className="flex gap-[24px] items-start w-full"><Link to="/support-technical-videos-2" className="group bg-white border border-[rgba(227,190,186,0.3)] border-solid drop-shadow-[0px_4px_10px_rgba(0,0,0,0.05)] flex flex-col items-start p-px relative rounded-[24px] shrink-0 w-[416px] cursor-pointer hover:border-[#fd022c] transition-colors">
        <div className="h-[304px] relative rounded-[24px] shrink-0 w-full"><img alt="How to access camera  \u2013 video thumbnail" className="absolute inset-0 max-w-none object-cover pointer-events-none rounded-[24px] size-full" src={img0a245a08615e} /></div>
        <div className="flex flex-col items-start p-[24px] w-full"><h3 className="font-['Inter'] font-medium leading-[1.2] text-[#111] text-[18px] w-full group-hover:text-[#fd022c]">How to access camera </h3></div>
        <div className="absolute left-[171px] size-[72px] top-[116px] transition-transform group-hover:scale-110"><img alt="" className="absolute block inset-0 max-w-none size-full" src={imgd58418bbc3a0} /></div>
        <div className="absolute bg-[rgba(17,17,17,0.8)] flex items-center justify-center left-[348px] px-[4px] py-[2px] rounded-[4px] top-[269px]"><p className="font-['Inter'] font-medium leading-[1.2] text-[16px] text-white whitespace-nowrap">02:18</p></div>
      </Link><Link to="/support-technical-videos-2" className="group bg-white border border-[rgba(227,190,186,0.3)] border-solid drop-shadow-[0px_4px_10px_rgba(0,0,0,0.05)] flex flex-col items-start p-px relative rounded-[24px] shrink-0 w-[416px] cursor-pointer hover:border-[#fd022c] transition-colors">
        <div className="h-[304px] relative rounded-[24px] shrink-0 w-full"><img alt="How to backup recording from Camera \u2013 video thumbnail" className="absolute inset-0 max-w-none object-cover pointer-events-none rounded-[24px] size-full" src={img0a245a08615e} /></div>
        <div className="flex flex-col items-start p-[24px] w-full"><h3 className="font-['Inter'] font-medium leading-[1.2] text-[#111] text-[18px] w-full group-hover:text-[#fd022c]">How to backup recording from Camera</h3></div>
        <div className="absolute left-[171px] size-[72px] top-[116px] transition-transform group-hover:scale-110"><img alt="" className="absolute block inset-0 max-w-none size-full" src={imgd58418bbc3a0} /></div>
        <div className="absolute bg-[rgba(17,17,17,0.8)] flex items-center justify-center left-[348px] px-[4px] py-[2px] rounded-[4px] top-[269px]"><p className="font-['Inter'] font-medium leading-[1.2] text-[16px] text-white whitespace-nowrap">02:18</p></div>
      </Link><Link to="/support-technical-videos-2" className="group bg-white border border-[rgba(227,190,186,0.3)] border-solid drop-shadow-[0px_4px_10px_rgba(0,0,0,0.05)] flex flex-col items-start p-px relative rounded-[24px] shrink-0 w-[416px] cursor-pointer hover:border-[#fd022c] transition-colors">
        <div className="h-[304px] relative rounded-[24px] shrink-0 w-full"><img alt="How to configure \u2013 video thumbnail" className="absolute inset-0 max-w-none object-cover pointer-events-none rounded-[24px] size-full" src={img0a245a08615e} /></div>
        <div className="flex flex-col items-start p-[24px] w-full"><h3 className="font-['Inter'] font-medium leading-[1.2] text-[#111] text-[18px] w-full group-hover:text-[#fd022c]">How to configure</h3></div>
        <div className="absolute left-[171px] size-[72px] top-[116px] transition-transform group-hover:scale-110"><img alt="" className="absolute block inset-0 max-w-none size-full" src={imgd58418bbc3a0} /></div>
        <div className="absolute bg-[rgba(17,17,17,0.8)] flex items-center justify-center left-[348px] px-[4px] py-[2px] rounded-[4px] top-[269px]"><p className="font-['Inter'] font-medium leading-[1.2] text-[16px] text-white whitespace-nowrap">02:18</p></div>
      </Link></div>
      </section>
      <section className="flex flex-col gap-[32px] items-start w-full">
        <div className="flex items-center justify-between w-full"><h2 className="font-['Poppins'] leading-[1.2] text-[#111] text-[24px] whitespace-nowrap">gCMOB</h2><Link to="/support-technical-videos-2" className="font-['Inter'] font-medium leading-[24px] text-[#111] text-[16px] whitespace-nowrap hover:text-[#fd022c]">See All</Link></div>
        <div className="flex gap-[24px] items-start w-full"><Link to="/support-technical-videos-2" className="group bg-white border border-[rgba(227,190,186,0.3)] border-solid drop-shadow-[0px_4px_10px_rgba(0,0,0,0.05)] flex flex-col items-start p-px relative rounded-[24px] shrink-0 w-[416px] cursor-pointer hover:border-[#fd022c] transition-colors">
        <div className="h-[304px] relative rounded-[24px] shrink-0 w-full"><img alt="How to enable Push \u2013 video thumbnail" className="absolute inset-0 max-w-none object-cover pointer-events-none rounded-[24px] size-full" src={img0a245a08615e} /></div>
        <div className="flex flex-col items-start p-[24px] w-full"><h3 className="font-['Inter'] font-medium leading-[1.2] text-[#111] text-[18px] w-full group-hover:text-[#fd022c]">How to enable Push</h3></div>
        <div className="absolute left-[171px] size-[72px] top-[116px] transition-transform group-hover:scale-110"><img alt="" className="absolute block inset-0 max-w-none size-full" src={imgd58418bbc3a0} /></div>
        <div className="absolute bg-[rgba(17,17,17,0.8)] flex items-center justify-center left-[348px] px-[4px] py-[2px] rounded-[4px] top-[269px]"><p className="font-['Inter'] font-medium leading-[1.2] text-[16px] text-white whitespace-nowrap">02:18</p></div>
      </Link><Link to="/support-technical-videos-2" className="group bg-white border border-[rgba(227,190,186,0.3)] border-solid drop-shadow-[0px_4px_10px_rgba(0,0,0,0.05)] flex flex-col items-start p-px relative rounded-[24px] shrink-0 w-[416px] cursor-pointer hover:border-[#fd022c] transition-colors">
        <div className="h-[304px] relative rounded-[24px] shrink-0 w-full"><img alt="How to Manage Schedule \u2013 video thumbnail" className="absolute inset-0 max-w-none object-cover pointer-events-none rounded-[24px] size-full" src={img0a245a08615e} /></div>
        <div className="flex flex-col items-start p-[24px] w-full"><h3 className="font-['Inter'] font-medium leading-[1.2] text-[#111] text-[18px] w-full group-hover:text-[#fd022c]">How to Manage Schedule</h3></div>
        <div className="absolute left-[171px] size-[72px] top-[116px] transition-transform group-hover:scale-110"><img alt="" className="absolute block inset-0 max-w-none size-full" src={imgd58418bbc3a0} /></div>
        <div className="absolute bg-[rgba(17,17,17,0.8)] flex items-center justify-center left-[348px] px-[4px] py-[2px] rounded-[4px] top-[269px]"><p className="font-['Inter'] font-medium leading-[1.2] text-[16px] text-white whitespace-nowrap">02:18</p></div>
      </Link><Link to="/support-technical-videos-2" className="group bg-white border border-[rgba(227,190,186,0.3)] border-solid drop-shadow-[0px_4px_10px_rgba(0,0,0,0.05)] flex flex-col items-start p-px relative rounded-[24px] shrink-0 w-[416px] cursor-pointer hover:border-[#fd022c] transition-colors">
        <div className="h-[304px] relative rounded-[24px] shrink-0 w-full"><img alt="How to modify schedule \u2013 video thumbnail" className="absolute inset-0 max-w-none object-cover pointer-events-none rounded-[24px] size-full" src={img0a245a08615e} /></div>
        <div className="flex flex-col items-start p-[24px] w-full"><h3 className="font-['Inter'] font-medium leading-[1.2] text-[#111] text-[18px] w-full group-hover:text-[#fd022c]">How to modify schedule</h3></div>
        <div className="absolute left-[171px] size-[72px] top-[116px] transition-transform group-hover:scale-110"><img alt="" className="absolute block inset-0 max-w-none size-full" src={imgd58418bbc3a0} /></div>
        <div className="absolute bg-[rgba(17,17,17,0.8)] flex items-center justify-center left-[348px] px-[4px] py-[2px] rounded-[4px] top-[269px]"><p className="font-['Inter'] font-medium leading-[1.2] text-[16px] text-white whitespace-nowrap">02:18</p></div>
      </Link></div>
      </section>
      </div>
    </>
  );
}
