import { Link } from 'react-router-dom';
import img718f01ed0bc4 from '@/assets/718f01ed0bc4.svg';
import img0af695c0286e from '@/assets/0af695c0286e.webp';
import img4085fcd3b5d8 from '@/assets/4085fcd3b5d8.webp';
import img41f0e7c3506c from '@/assets/41f0e7c3506c.svg';
import img00106048fb0b from '@/assets/00106048fb0b.svg';
import imgd840b22a896e from '@/assets/d840b22a896e.svg';
import img45c86ca89d93 from '@/assets/45c86ca89d93.webp';
import img1243c860a694 from '@/assets/1243c860a694.svg';

export default function CapabilitiesSection() {
  return (
    <>
      <div className="content-stretch flex flex-col items-start relative size-full">
        <div className="bg-[#fff1f2] content-start flex flex-wrap items-start overflow-clip p-[72px] relative shrink-0 w-full">
          <div className="content-stretch flex flex-[1_0_0] gap-[48px] items-center justify-center max-w-[1440px] min-w-px relative">
            <div className="content-stretch flex flex-[1_0_0] flex-col gap-[12px] items-start min-w-px relative">
              <div className="[word-break:break-word] flex flex-col justify-center leading-[0] not-italic relative shrink-0 font-['Inter'] font-bold text-[#fd022c] text-[14px] tracking-[1.4px] uppercase whitespace-nowrap"><p className="leading-[20px]">Automatic Number Plate Recognition</p></div>
              <div className="[word-break:break-word] flex flex-col font-['Roboto'] font-semibold justify-center leading-[0] relative shrink-0 text-[#111] text-[32px] w-full whitespace-pre-wrap" style={{ fontVariationSettings: "'wdth' 100" }}><p className="leading-[1.2] mb-0">Identify Every Vehicle. </p><p className="leading-[1.2]">Capture Every Detail.</p></div>
              <div className="content-stretch flex flex-col items-start pt-[12px] relative shrink-0 w-full"><div className="[word-break:break-word] flex flex-col justify-center leading-[0] not-italic relative shrink-0 font-['Inter'] font-normal text-[#5f6368] text-[16px] w-full"><p className="leading-[1.5] mb-0">Our industry-leading ANPR algorithms capture and interpret</p><p className="leading-[1.5] mb-0">license plates across diverse conditions&mdash;from blinding glare and</p><p className="leading-[1.5] mb-0">total darkness to extreme speeds and complex vehicle angles.</p><p className="leading-[1.5] mb-0">We don&apos;t just read plates; we identify vehicle class, color, make,</p><p className="leading-[1.5]">and model in a fraction of a second.</p></div></div>
              <div className="content-stretch flex flex-col gap-[12px] items-start py-[36px] relative shrink-0 w-full">
                <div className="content-stretch flex gap-[12px] items-start relative shrink-0 w-full"><div className="relative shrink-0 size-[20px]"><img alt="" className="absolute block inset-0 max-w-none size-full" src={img718f01ed0bc4} /></div><div className="[word-break:break-word] flex flex-col justify-center leading-[0] not-italic relative shrink-0 font-['Inter'] font-medium text-[#111] text-[16px] whitespace-nowrap"><p className="leading-[1.2]">99.8% read accuracy in real-world scenarios</p></div></div>
                <div className="content-stretch flex gap-[12px] items-start relative shrink-0 w-full"><div className="relative shrink-0 size-[20px]"><img alt="" className="absolute block inset-0 max-w-none size-full" src={img718f01ed0bc4} /></div><div className="[word-break:break-word] flex flex-col justify-center leading-[0] not-italic relative shrink-0 font-['Inter'] font-medium text-[#111] text-[16px] whitespace-nowrap"><p className="leading-[1.2]">Captures plates at speeds up to 150 mph (240 km/h)</p></div></div>
                <div className="content-stretch flex gap-[12px] items-start relative shrink-0 w-full"><div className="relative shrink-0 size-[20px]"><img alt="" className="absolute block inset-0 max-w-none size-full" src={img718f01ed0bc4} /></div><div className="[word-break:break-word] flex flex-col justify-center leading-[0] not-italic relative shrink-0 font-['Inter'] font-medium text-[#111] text-[16px] whitespace-nowrap"><p className="leading-[1.2]">Supports multiple formats and international plates</p></div></div>
              </div>
            </div>
            <div className="bg-[#3f4347] content-stretch flex flex-[1_0_0] flex-col h-[340.934px] items-start min-w-px overflow-clip relative rounded-[24px]">
              <div className="aspect-[558/304.06] relative shrink-0 w-full"><div className="absolute inset-0 overflow-hidden pointer-events-none"><img alt="ANPR camera reading license plates" className="absolute left-0 max-w-none size-full top-0" src={img0af695c0286e} /></div></div>
              <div className="absolute backdrop-blur-[2px] bg-[rgba(0,82,209,0.2)] border-2 border-[#0052d1] border-solid content-stretch flex items-center p-[10px] absolute inset-[30.13%_47.75%_50.27%_20.1%] rounded-[4px] shadow-[0px_10px_15px_-3px_rgba(0,0,0,0.1),0px_4px_6px_-4px_rgba(0,0,0,0.1)]">
                <div className="content-stretch flex flex-col items-start relative shrink-0"><div className="[word-break:break-word] flex flex-col justify-center leading-[0] not-italic relative shrink-0 font-['Inter'] font-bold text-[12px] text-white tracking-[0.6px] whitespace-nowrap"><p className="leading-[18px]">ABC-1234</p></div><div className="[word-break:break-word] flex flex-col justify-center leading-[0] not-italic relative shrink-0 font-['Inter'] font-normal text-[10px] text-[rgba(255,255,255,0.8)] whitespace-nowrap"><p className="leading-[15px]">Sedan &bull; Blue &bull; 98%</p></div></div>
              </div>
              <div className="absolute backdrop-blur-[2px] bg-[rgba(0,82,209,0.2)] border-2 border-[#0052d1] border-solid content-stretch flex items-center p-[10px] absolute inset-[60.2%_10.14%_20.2%_57.71%] rounded-[4px] shadow-[0px_10px_15px_-3px_rgba(0,0,0,0.1),0px_4px_6px_-4px_rgba(0,0,0,0.1)]">
                <div className="content-stretch flex flex-col items-start relative shrink-0"><div className="[word-break:break-word] flex flex-col justify-center leading-[0] not-italic relative shrink-0 font-['Inter'] font-bold text-[12px] text-white tracking-[0.6px] whitespace-nowrap"><p className="leading-[18px]">XYZ-9876</p></div><div className="[word-break:break-word] flex flex-col justify-center leading-[0] not-italic relative shrink-0 font-['Inter'] font-normal text-[10px] text-[rgba(255,255,255,0.8)] whitespace-nowrap"><p className="leading-[15px]">SUV &bull; Black &bull; 96%</p></div></div>
              </div>
            </div>
          </div>
        </div>
        <div className="bg-white content-start flex flex-wrap gap-0 items-start overflow-clip px-[72px] py-[120px] relative shrink-0 w-full">
          <div className="absolute inset-[0_0_-0.26px_0] opacity-10"><div className="absolute bg-[#2f80ed] blur-[50px] bottom-[-300px] left-[-200px] rounded-[9999px] size-[600px]" /></div>
          <div className="content-stretch flex flex-[1_0_0] gap-[48px] items-end max-w-[1440px] min-w-px relative">
            <div className="bg-[#3f4347] content-stretch flex flex-col h-[354.744px] items-start overflow-clip relative rounded-[24px] shrink-0 w-[636px]">
              <div className="aspect-[648.66/353.45] mix-blend-luminosity opacity-80 relative rounded-[12px] shrink-0 w-full"><div className="absolute inset-0 overflow-hidden pointer-events-none rounded-[12px]"><img alt="Radar speed detection camera view" className="absolute h-[100.01%] left-0 max-w-none top-0 w-full" src={img4085fcd3b5d8} /></div></div>
              <div className="absolute inset-[1px_1.34px_0.29px_1px]">
                <div className="content-stretch flex items-center justify-center relative size-full">
                  <div className="flex-[1_0_0] h-[369.45px] min-w-px overflow-clip relative">
                    <div className="absolute inset-[28.63%_16.65%_11.37%_16.65%]"><div className="absolute inset-[0_-4.89%_0_0]"><img alt="" className="block max-w-none size-full" src={img41f0e7c3506c} /></div></div>
                    <div className="absolute inset-[48.63%_44.44%_39.37%_44.44%]"><div className="absolute inset-[-1.67%_-5.94%_-1.67%_-1.05%]"><img alt="" className="block max-w-none size-full" src={img00106048fb0b} /></div></div>
                    <div className="absolute h-[8.867px] left-[295.38px] top-[166.93px] w-[31.92px]"><div className="-translate-y-1/2 [word-break:break-word] absolute flex flex-col font-['Nimbus_Mono_PS'] font-mono font-bold h-[8.867px] justify-center leading-[0] left-0 not-italic text-[#0f0] text-[8.867px] top-[4.43px] w-[31.92px]"><p className="leading-[normal]">72 MPH</p></div></div>
                    <div className="absolute inset-[63.23%_25.54%_20.77%_61.12%]"><div className="absolute inset-[-1.25%_-5.77%_-1.25%_-0.87%]"><img alt="" className="block max-w-none size-full" src={imgd840b22a896e} /></div></div>
                    <div className="absolute h-[8.867px] left-[406.22px] top-[220.88px] w-[95.761px]"><div className="-translate-y-1/2 [word-break:break-word] absolute flex flex-col font-['Nimbus_Mono_PS'] font-mono font-bold h-[8.867px] justify-center leading-[0] left-0 not-italic text-[#f33] text-[8.867px] top-[4.43px] w-[95.761px]"><p className="leading-[normal]">85 MPH (VIOLATION)</p></div></div>
                  </div>
                </div>
              </div>
            </div>
            <div className="content-stretch flex flex-[1_0_0] flex-col gap-[24px] items-start min-w-px relative">
              <div className="[word-break:break-word] flex flex-col justify-center leading-[0] not-italic relative shrink-0 font-['Inter'] font-bold text-[#fd022c] text-[14px] tracking-[1.4px] uppercase whitespace-nowrap"><p className="leading-[20px]">RADAR INTEGRATION</p></div>
              <div className="content-stretch flex flex-col items-start pb-[12px] relative shrink-0 w-full"><div className="[word-break:break-word] flex flex-col font-['Roboto'] font-semibold justify-center leading-[0] relative shrink-0 text-[#111] text-[32px] w-full whitespace-pre-wrap" style={{ fontVariationSettings: "'wdth' 100" }}><p className="leading-[1.2]">Measure Speed. Improve Road Safety.</p></div></div>
              <div className="content-stretch flex flex-col items-start pb-[24px] relative shrink-0 w-full"><div className="[word-break:break-word] flex flex-col justify-center leading-[0] not-italic relative shrink-0 font-['Inter'] font-normal text-[#5f6368] text-[16px] w-full"><p className="leading-[1.5]">HOUM&rsquo;s Radar Speed Enforcement Solution provides accurate speed monitoring across multiple lanes and traffic environments. By combining radar-based detection with vehicle identification and centralized monitoring, authorities can identify speeding vehicles and maintain reliable enforcement records.</p></div></div>
              <div className="h-[80px] relative shrink-0 w-full">
                <div className="absolute backdrop-blur-[2px] bg-[#fff1f2] border border-[#f22f38] border-solid bottom-[46px] left-0 top-0 content-stretch flex flex-col items-start px-[13px] py-[9px] rounded-[9999px]"><div className="[word-break:break-word] flex flex-col justify-center leading-[0] not-italic relative shrink-0 font-['Inter'] font-medium text-[#111] text-[14px] tracking-[0.14px] whitespace-nowrap"><p className="leading-[16px]">Multi-Lane Detection</p></div></div>
                <div className="absolute backdrop-blur-[2px] bg-[#fff1f2] border border-[#f22f38] border-solid bottom-[46px] left-[181.17px] top-0 content-stretch flex flex-col items-start px-[13px] py-[9px] rounded-[9999px]"><div className="[word-break:break-word] flex flex-col justify-center leading-[0] not-italic relative shrink-0 font-['Inter'] font-medium text-[#111] text-[14px] tracking-[0.14px] whitespace-nowrap"><p className="leading-[16px]">Accurate Speed Measurement</p></div></div>
                <div className="absolute backdrop-blur-[2px] bg-[#fff1f2] border border-[#f22f38] border-solid bottom-0 left-0 top-[46px] content-stretch flex flex-col items-start px-[13px] py-[9px] rounded-[9999px]"><div className="[word-break:break-word] flex flex-col justify-center leading-[0] not-italic relative shrink-0 font-['Inter'] font-medium text-[#111] text-[14px] tracking-[0.14px] whitespace-nowrap"><p className="leading-[16px]">Vehicle Classification</p></div></div>
                <div className="absolute backdrop-blur-[2px] bg-[#fff1f2] border border-[#f22f38] border-solid bottom-0 left-[184.56px] top-[46px] content-stretch flex flex-col items-start px-[13px] py-[9px] rounded-[9999px]"><div className="[word-break:break-word] flex flex-col justify-center leading-[0] not-italic relative shrink-0 font-['Inter'] font-medium text-[#111] text-[14px] tracking-[0.14px] whitespace-nowrap"><p className="leading-[16px]">Evidence Capture</p></div></div>
              </div>
            </div>
          </div>
        </div>
        <div className="bg-[#fff1f2] content-start flex flex-wrap items-start overflow-clip p-[72px] relative shrink-0 w-full">
          <div className="content-stretch flex flex-[1_0_0] gap-[48px] items-end justify-center max-w-[1440px] min-w-px relative">
            <div className="content-stretch flex flex-[1_0_0] flex-col gap-[12px] items-start min-w-px relative">
              <div className="[word-break:break-word] flex flex-col justify-center leading-[0] not-italic relative shrink-0 font-['Inter'] font-bold text-[#fd022c] text-[14px] tracking-[1.4px] uppercase whitespace-nowrap"><p className="leading-[20px]">AUTOMATED ENFORCEMENT</p></div>
              <div className="[word-break:break-word] flex flex-col font-['Roboto'] font-semibold justify-center leading-[0] relative shrink-0 text-[#111] text-[32px] w-full whitespace-pre-wrap" style={{ fontVariationSettings: "'wdth' 100" }}><p className="leading-[1.2]">Detect Signal Violations. Strengthen Road Safety.</p></div>
              <div className="content-stretch flex flex-col items-start pt-[12px] relative shrink-0 w-full"><div className="[word-break:break-word] flex flex-col justify-center leading-[0] not-italic relative shrink-0 font-['Inter'] font-normal text-[#5f6368] text-[16px] w-full"><p className="leading-[1.5]">HOUM&rsquo;s Red-Light Enforcement Solution combines video monitoring and radar-based detection to identify vehicles crossing intersections against traffic signals. Recorded vehicle information and evidence help authorities improve compliance and support effective traffic enforcement.</p></div></div>
              <div className="gap-x-[12px] gap-y-[12px] grid grid-cols-[repeat(2,minmax(0,1fr))] grid-rows-[46px_46px] pt-[36px] relative shrink-0 w-full">
                <div className="bg-white border border-[#e5e5e5] border-solid col-1 row-1 content-stretch flex h-[46px] items-center justify-self-stretch p-[13px] relative rounded-[8px] shrink-0"><div className="[word-break:break-word] flex flex-col justify-center leading-[0] not-italic relative shrink-0 font-['Inter'] font-normal text-[#111] text-[14px] whitespace-nowrap"><p className="leading-[20px]">Signal status sync</p></div></div>
                <div className="bg-white border border-[#e5e5e5] border-solid col-2 row-1 content-stretch flex h-[46px] items-center justify-self-stretch p-[13px] relative rounded-[8px] shrink-0"><div className="[word-break:break-word] flex flex-col justify-center leading-[0] not-italic relative shrink-0 font-['Inter'] font-normal text-[#111] text-[14px] whitespace-nowrap"><p className="leading-[20px]">Vehicle trajectory</p></div></div>
                <div className="bg-white border border-[#e5e5e5] border-solid col-1 row-2 content-stretch flex h-[46px] items-center justify-self-stretch p-[13px] relative rounded-[8px] shrink-0"><div className="[word-break:break-word] flex flex-col justify-center leading-[0] not-italic relative shrink-0 font-['Inter'] font-normal text-[#111] text-[14px] whitespace-nowrap"><p className="leading-[20px]">Evidence packaging</p></div></div>
                <div className="bg-white border border-[#e5e5e5] border-solid col-2 row-2 content-stretch flex h-[46px] items-center justify-self-stretch p-[13px] relative rounded-[8px] shrink-0"><div className="[word-break:break-word] flex flex-col justify-center leading-[0] not-italic relative shrink-0 font-['Inter'] font-normal text-[#111] text-[14px] whitespace-nowrap"><p className="leading-[20px]">Automated alerts</p></div></div>
              </div>
            </div>
            <div className="bg-[#3f4347] content-stretch flex flex-[1_0_0] flex-col h-[351.854px] items-start min-w-px overflow-clip relative rounded-[24px]">
              <div className="aspect-[534/290.98] relative rounded-[12px] shrink-0 w-full"><div className="absolute inset-0 overflow-hidden pointer-events-none rounded-[12px]"><img alt="Red-light enforcement camera view" className="absolute left-0 max-w-none size-full top-0" src={img45c86ca89d93} /></div></div>
              <div className="absolute backdrop-blur-[6px] bg-[rgba(255,255,255,0.95)] border border-[#e5eaf0] border-solid right-[25px] rounded-[12px] top-[25px] w-[240px] shadow-[0px_12px_24px_-8px_rgba(0,0,0,0.05)]">
                <div className="content-stretch flex flex-col gap-[12px] items-start p-[25px] relative size-full">
                  <div className="border-[#e5eaf0] border-b border-solid content-stretch flex gap-[12px] items-center pb-[13px] relative shrink-0 w-full"><div className="bg-[#ba1a1a] relative rounded-[9999px] shrink-0 size-[12px]" /><div className="[word-break:break-word] flex flex-col justify-center leading-[0] not-italic relative shrink-0 font-['Inter'] font-bold text-[#ba1a1a] text-[12px] tracking-[0.6px] uppercase whitespace-nowrap"><p className="leading-[16px]">VIOLATION DETECTED</p></div></div>
                  <div className="content-stretch flex flex-col gap-[4px] items-start relative shrink-0 w-full">
                  <div className="content-stretch flex items-start justify-between relative shrink-0 w-full"><div className="[word-break:break-word] flex flex-col justify-center leading-[0] not-italic relative shrink-0 font-['Inter'] font-semibold text-[#667085] text-[12px] tracking-[0.36px] whitespace-nowrap"><p className="leading-[16px]">Signal:</p></div><div className="[word-break:break-word] flex flex-col justify-center leading-[0] not-italic relative shrink-0 font-['Inter'] font-bold text-[#0b1728] text-[12px] tracking-[0.36px] whitespace-nowrap"><p className="leading-[16px]">RED (2.3s)</p></div></div>
                  <div className="content-stretch flex items-start justify-between relative shrink-0 w-full"><div className="[word-break:break-word] flex flex-col justify-center leading-[0] not-italic relative shrink-0 font-['Inter'] font-semibold text-[#667085] text-[12px] tracking-[0.36px] whitespace-nowrap"><p className="leading-[16px]">Time:</p></div><div className="[word-break:break-word] flex flex-col justify-center leading-[0] not-italic relative shrink-0 font-['Inter'] font-bold text-[#0b1728] text-[12px] tracking-[0.36px] whitespace-nowrap"><p className="leading-[16px]">14:32:05</p></div></div>
                  <div className="content-stretch flex items-start justify-between relative shrink-0 w-full"><div className="[word-break:break-word] flex flex-col justify-center leading-[0] not-italic relative shrink-0 font-['Inter'] font-semibold text-[#667085] text-[12px] tracking-[0.36px] whitespace-nowrap"><p className="leading-[16px]">Plate:</p></div><div className="[word-break:break-word] flex flex-col justify-center leading-[0] not-italic relative shrink-0 font-['Inter'] font-bold text-[#0b1728] text-[12px] tracking-[0.36px] whitespace-nowrap"><p className="leading-[16px]">LMN-4567</p></div></div>
                  </div>
                  <Link to="/sol-smart-traffic" className="bg-[#dbe1ff] hover:bg-[#c8d1ff] content-stretch flex gap-[4px] items-center justify-center py-[8px] relative rounded-[4px] shrink-0 w-full"><div className="h-[10px] relative shrink-0 w-[14.667px]"><img alt="" className="absolute block inset-0 max-w-none size-full" src={img1243c860a694} /></div><div className="[word-break:break-word] flex flex-col justify-center leading-[0] not-italic relative shrink-0 font-['Inter'] font-normal text-[#003fa5] text-[16px] text-center whitespace-nowrap"><p className="leading-[24px]">View Evidence</p></div></Link>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </>
  );
}
